@echo off
REM ============================================================
REM WebGIS 本地开发一键启动脚本 v3.0
REM 支持自动依赖检查、自动打开浏览器
REM 前端：http://localhost:5173
REM 后端：http://localhost:7860
REM ============================================================

REM 设置代码页为 UTF-8 以支持中文显示
chcp 65001 >nul 2>&1

setlocal enabledelayedexpansion

cls
echo.
echo ====================================================================
echo   WebGIS 本地开发一键启动脚本 v3.0
echo ====================================================================
echo.

REM 获取当前脚本所在目录
set PROJECT_ROOT=%~dp0
set FRONTEND_DIR=%PROJECT_ROOT%frontend
set BACKEND_DIR=%PROJECT_ROOT%backend

REM ====================================================================
REM 第一步：检查环境依赖
REM ====================================================================
echo [第一步] 检查环境依赖...
echo.

REM --------------------------------------------------
REM 1. 检查 Node.js / npm（前端依赖）
REM --------------------------------------------------
where node >nul 2>&1
if errorlevel 1 (
    echo [错误] Node.js 未安装！
    echo        下载地址: https://nodejs.org/
    pause
    exit /b 1
)

for /f "tokens=*" %%i in ('node -v') do set NODE_VERSION=%%i
echo   ✓ Node.js %NODE_VERSION% 已安装

where npm >nul 2>&1
if errorlevel 1 (
    echo [错误] npm 未安装！
    pause
    exit /b 1
)

for /f "tokens=*" %%i in ('npm -v') do set NPM_VERSION=%%i
echo   ✓ npm %NPM_VERSION% 已安装

echo.

REM --------------------------------------------------
REM 2. 检查 Docker
REM --------------------------------------------------
where docker >nul 2>&1
if errorlevel 1 (
    echo [错误] 未检测到 Docker！
    echo        请安装 Docker Desktop:
    echo        https://www.docker.com/products/docker-desktop/
    pause
    exit /b 1
)

echo   ✓ Docker 已安装

REM --------------------------------------------------
REM 3. 检查 Docker 是否运行
REM --------------------------------------------------
docker info >nul 2>&1
if errorlevel 1 (
    echo [警告] Docker 未启动，尝试自动启动...

    start "" "C:\Program Files\Docker\Docker\Docker Desktop.exe"

    echo   正在等待 Docker 启动（约 15 秒）...
    timeout /t 15 /nobreak >nul

    docker info >nul 2>&1
    if errorlevel 1 (
        echo [错误] Docker 启动失败，请手动启动！
        pause
        exit /b 1
    )
)

echo   ✓ Docker 运行正常

echo.

REM --------------------------------------------------
REM 4. 检查 docker compose
REM --------------------------------------------------
docker compose version >nul 2>&1
if errorlevel 1 (
    echo [错误] docker compose 不可用！
    pause
    exit /b 1
)

echo   ✓ docker compose 可用

echo.
echo [✓] 环境检查完成
echo.

REM ====================================================================
REM 第二步：配置前端环境变量 
REM ====================================================================
echo [第二步] 配置前端环境变量...
echo.

REM 确保前端目录变量被正确引用（加双引号防止空格报错）
set "FRONTEND_DIR=%PROJECT_ROOT%frontend"
set "ENV_FILE=%FRONTEND_DIR%\.env.local"

REM 检查前端文件夹是否存在，不存在则先创建（防止写入失败）
if not exist "%FRONTEND_DIR%" (
    echo   [警告] 未找到前端目录: %FRONTEND_DIR%
    echo          正在尝试创建该目录...
    mkdir "%FRONTEND_DIR%"
)

REM 检查是否存在 .env.local，如果不存在则创建
if not exist "%ENV_FILE%" (
    echo   正在创建前端环境配置文件...
    
    REM 使用括号重定向，注意每一行内部不要有奇怪的特殊字符
    (
        echo # WebGIS 前端环境配置（本地开发）
        echo # Auto generated by LocalDev.bat(脚本自动生成)
        echo.
        echo VITE_BACKEND_URL = http://localhost:7860
        echo VITE_TIANDITU_TK = your_tianditu_token_here
        echo.
        echo # 提示:此文件由脚本自动生成,仅本地开发使用,勿提交到git仓库 
        echo # 生产环境请使用 .env.production 配置。
        echo # 项目中使用的高德地图api key、LLM API key、需要用admin身份登陆
        echo # 在账户中心里使用admin身份,配置其它后端环境变量，自动注入后端数据库中
        echo # 部署环境同上,需admin身份先配置环境到数据库中,供所有用户使用
    ) > "%ENV_FILE%"
    REM 检查文件是否真的生成成功
    if exist "%ENV_FILE%" (
        echo   ✓ 配置文件已成功创建于: %ENV_FILE%
    ) else (
        echo   [错误] 无法创建配置文件，请检查磁盘权限！
    )
) else (
    echo   ✓ 配置文件已存在，跳过创建。
)
echo.

REM ====================================================================
REM 第三步：启动后端服务（Docker Compose）
REM ====================================================================
echo [第三步] 启动后端服务 (Docker Compose)...
echo   地址: http://localhost:7860
echo.

cd /d "%BACKEND_DIR%"

REM --------------------------------------------------
REM 1. 检查 docker-compose.yml 是否存在（唯一必要校验）
REM --------------------------------------------------
if not exist "docker-compose.yml" (
    echo [错误] 未找到 docker-compose.yml！
    echo        请确认后端目录结构是否正确
    pause
    exit /b 1
)

REM --------------------------------------------------
REM 2. 启动容器（后台模式）
REM --------------------------------------------------
echo   正在启动后端容器...
echo.

docker compose up -d

if errorlevel 1 (
    echo [错误] 后端启动失败！（docker compose up 执行失败）
    pause
    exit /b 1
)

REM --------------------------------------------------
REM 3. 简单等待（避免前端过早请求）
REM --------------------------------------------------
echo   等待服务初始化...
timeout /t 5 /nobreak >nul

REM --------------------------------------------------
REM 4. 检查容器状态
REM --------------------------------------------------
docker compose ps | findstr "Up" >nul
if errorlevel 1 (
    echo [警告] 容器未完全启动，请检查日志：
    echo        docker compose logs
) else (
    echo   ✓ 后端容器运行中
)

REM --------------------------------------------------
REM 5. 端口检测（兜底）
REM --------------------------------------------------
netstat -ano | findstr :7860 >nul
if errorlevel 1 (
    echo [警告] 7860 端口尚未监听（可能仍在启动中）
) else (
    echo   ✓ 后端服务端口已就绪
)

echo.

REM ====================================================================
REM 第四步：配置并启动前端服务
REM ====================================================================
echo [第四步] 配置前端项目...
echo.

cd /d "%FRONTEND_DIR%"

REM 检查 node_modules 是否存在
if not exist "node_modules" (
    echo [重要] 未找到 node_modules，正在安装依赖项...
    echo   这可能需要 1-5 分钟，请耐心等待...
    echo.
    call npm install --no-audit --no-fund
    if errorlevel 1 (
        echo [错误] npm install 失败！
        echo   请检查网络连接或手动运行: cd frontend && npm install
        echo   按任意键退出...
        pause
        exit /b 1
    )
    echo   ✓ 前端依赖已安装
    echo.
) else (
    echo   ✓ 前端依赖已存在
    echo.
)

echo [第五步] 启动前端开发服务 (Vite)...
echo   前端地址: http://localhost:5173
REM 自动获取本机局域网 IP地址，提示手机调试使用
for /f "tokens=4 delims= " %%i in ('route print ^| findstr 0.0.0.0 ^| findstr /V "127.0.0.1" ^| findstr /V "255.255.255.255"') do (
    set LOCAL_IP=%%i
    goto :IP_FOUND
)
:IP_FOUND
echo   局域网地址: http://%LOCAL_IP%:5173 (用于手机调试)
echo   提示: 按 Ctrl+C 可在前端窗口中停止前端服务
echo.

start "WebGIS Frontend" cmd /k "cd /d "%FRONTEND_DIR%" && npm run dev"

REM 等待前端服务启动
timeout /t 5 /nobreak

REM ====================================================================
REM 第六步：自动打开浏览器
REM ====================================================================
echo [第六步] 打开浏览器...
echo   提示: 按 Ctrl+C 可停止所有服务
echo.

REM 等待一下让 Vite 完全启动
timeout /t 3 /nobreak

REM 打开浏览器
start http://localhost:5173

echo.
echo ====================================================================
echo   启动完成！
echo ====================================================================
echo.
echo 前端 (Frontend):
echo   地址: http://localhost:5173
echo   功能: Vite 热重载启用（代码改动浏览器自动刷新）
echo.
echo 后端 (Backend):
echo   API:  http://localhost:7860
echo   API参考文档: http://localhost:7860/docs (Swagger UI，在此测试 API)
echo   功能: 自动重启启用（代码改动自动重启）
echo.
echo 数据流:
echo   前端 (http://localhost:5173)
echo        ^|
echo   调用后端 API (http://localhost:7860)
echo        ^|
echo   后端调用第三方服务 (AMap, TianDiTu 等)
echo        ^|
echo   返回统一 JSON 数据
echo.
echo 快速参考:
echo   1. 已打开所有窗口，关闭任意窗口可停止该服务
echo   2. 修改前端代码可自动热重载（浏览器自动刷新）
echo   3. 修改后端代码可自动重启
echo   4. 测试 API: 打开 http://localhost:7860/docs
echo   5. 前端调用后端 API 地址: http://localhost:7860
echo.
echo 停止服务:
echo   - 关闭后端窗口停止后端服务
echo   - 关闭前端窗口停止前端服务
echo   - 或在任意窗口按 Ctrl+C 并输入 Y 确认
echo.
echo 文档说明:
echo   - 集成指南: FRONTEND_BACKEND_INTEGRATION_GUIDE.md
echo   - API 参考: API_QUICK_REFERENCE.md
echo   - 后端实现: BACKEND_IMPLEMENTATION_GUIDE.md
echo   - 快速开始: QUICKSTART.md
echo.
echo ====================================================================
echo 提示: 按 Ctrl+C 可随时停止脚本 (输入 Y 确认)
echo ====================================================================
echo.

echo.
echo 按任意键退出此脚本（不会停止已启动的前端/后端服务）...
pause >nul

endlocal
