@echo off
REM ============================================================
REM WebGIS Local Dev Launcher v3.0
REM Frontend: http://localhost:5173
REM Backend:  http://localhost:7860
REM ============================================================

chcp 65001 >nul 2>&1
setlocal enabledelayedexpansion

REM Helper: call Write-Color.ps1 with message ID
set "WC=powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0Write-Color.ps1""

%WC% 100
%WC% 101
%WC% 102

set PROJECT_ROOT=%~dp0
set FRONTEND_DIR=%PROJECT_ROOT%frontend
set BACKEND_DIR=%PROJECT_ROOT%backend

REM ====================================================================
REM Step 1: Check dependencies
REM ====================================================================
%WC% 200
echo.

REM 1. Node.js / npm
where node >nul 2>&1
if errorlevel 1 goto :ERR_NODE

for /f "tokens=*" %%i in ('node -v') do set NODE_VERSION=%%i
%WC% 300 "!NODE_VERSION!"

where npm >nul 2>&1
if errorlevel 1 goto :ERR_NPM

for /f "tokens=*" %%i in ('npm -v') do set NPM_VERSION=%%i
%WC% 301 "!NPM_VERSION!"

echo.

REM 2. Docker
where docker >nul 2>&1
if errorlevel 1 goto :ERR_DOCKER

%WC% 302

REM 3. Docker running?
docker info >nul 2>&1
if errorlevel 1 (
    %WC% 500
    start "" "C:\Program Files\Docker\Docker\Docker Desktop.exe"
    %WC% 701
    timeout /t 15 /nobreak >nul
    docker info >nul 2>&1
    if errorlevel 1 goto :ERR_DOCKER_START
)

%WC% 303
echo.

REM 4. docker compose
docker compose version >nul 2>&1
if errorlevel 1 goto :ERR_COMPOSE

%WC% 304
echo.
%WC% 305
echo.

REM ====================================================================
REM Step 2: Frontend env config
REM ====================================================================
%WC% 201
echo.

set "FRONTEND_DIR=%PROJECT_ROOT%frontend"
set "ENV_FILE=%FRONTEND_DIR%\.env.local"

if not exist "%FRONTEND_DIR%" (
    %WC% 501
    mkdir "%FRONTEND_DIR%"
)

if not exist "%ENV_FILE%" (
    %WC% 702

    (
        echo # WebGIS Frontend Env Config (Local Dev)
        echo # Auto generated by LocalDev.bat
        echo.
        echo VITE_BACKEND_URL = http://localhost:7860
        echo VITE_TIANDITU_TK = your_tianditu_token_here
        echo.
        echo # This file is auto-generated for local dev only, do NOT commit to git
        echo # Production: use .env.production
        echo # Admin login required for AMap key, LLM key, and backend env vars
    ) > "%ENV_FILE%"

    if exist "%ENV_FILE%" (
        %WC% 306 "%ENV_FILE%"
    ) else (
        %WC% 409
    )
) else (
    %WC% 307
)
echo.

REM ====================================================================
REM Step 3: Start backend (Docker Compose)
REM ====================================================================
%WC% 202
%WC% 700
echo.

cd /d "%BACKEND_DIR%"

if not exist "docker-compose.yml" goto :ERR_COMPOSE_FILE

REM --- Smart image build detection ---
%WC% 703
echo.

set DOCKER_ACTION=up
set IMAGE_NAME=negiao/webgis_dev:latest

for /f "tokens=*" %%i in ('docker compose config --images 2^>nul') do (
    set IMAGE_NAME=%%i
    goto :GOT_IMAGE
)
:GOT_IMAGE

docker image inspect !IMAGE_NAME! >nul 2>&1
if errorlevel 1 (
    %WC% 600
    set DOCKER_ACTION=build
    goto :DO_DOCKER
)

REM Compare Dockerfile time vs image creation time
for /f "tokens=*" %%t in ('docker inspect --format "{{.Created}}" !IMAGE_NAME! 2^>nul') do (
    > "%TEMP%\wc_img_time.txt" echo %%t
)
set /p IMG_TIME=<"%TEMP%\wc_img_time.txt"

%WC% 704 "!IMG_TIME!"

powershell -NoProfile -Command "$img=[DateTime]::Parse((Get-Content '%TEMP%\wc_img_time.txt'));$f=(Get-Item 'Dockerfile').LastWriteTime;if($f-gt$img){exit 1}else{exit 0}"

if errorlevel 1 (
    echo.
    %WC% 502
    %WC% 705
    echo.
    %WC% 603
    set /p REBUILD_CHOICE=
    if /I "!REBUILD_CHOICE!"=="Y" (
        set DOCKER_ACTION=build
    ) else (
        %WC% 601
    )
) else (
    %WC% 308
)

:DO_DOCKER
echo.
%WC% 706

if "!DOCKER_ACTION!"=="build" (
    docker compose up --build -d
    if errorlevel 1 goto :ERR_BACKEND_BUILD
) else (
    docker compose up -d
    if errorlevel 1 goto :ERR_BACKEND_UP
)

%WC% 707
timeout /t 5 /nobreak >nul

docker compose ps | findstr "Up" >nul
if errorlevel 1 (
    %WC% 503
) else (
    %WC% 309
)

netstat -ano | findstr :7860 >nul
if errorlevel 1 (
    %WC% 504
) else (
    %WC% 310
)

echo.

REM ====================================================================
REM Step 4: Frontend setup
REM ====================================================================
%WC% 203
echo.

cd /d "%FRONTEND_DIR%"

if not exist "node_modules" (
    %WC% 505
    %WC% 730
    echo.
    call npm install --no-audit --no-fund
    if errorlevel 1 goto :ERR_NPM_INSTALL
    %WC% 311
    echo.
) else (
    %WC% 312
    echo.
)

REM ====================================================================
REM Step 5: Start frontend (Vite)
REM ====================================================================
%WC% 204
%WC% 708

for /f "tokens=4 delims= " %%i in ('route print ^| findstr 0.0.0.0 ^| findstr /V "127.0.0.1" ^| findstr /V "255.255.255.255"') do (
    set LOCAL_IP=%%i
    goto :IP_FOUND
)
:IP_FOUND
%WC% 602 "http://!LOCAL_IP!:5173"
%WC% 709
echo.

start "WebGIS Frontend" cmd /k "cd /d "%FRONTEND_DIR%" && npm run dev"

timeout /t 5 /nobreak

REM ====================================================================
REM Step 6: Open browser
REM ====================================================================
%WC% 205
%WC% 710
echo.

timeout /t 3 /nobreak

start http://localhost:5173

echo.
%WC% 100
%WC% 313
%WC% 102
echo.
%WC% 800
%WC% 900
%WC% 711
echo.
%WC% 801
%WC% 901
%WC% 902
%WC% 712
echo.
%WC% 802
%WC% 903
%WC% 713
%WC% 904
%WC% 713
%WC% 714
%WC% 713
%WC% 715
echo.
%WC% 803
%WC% 716
%WC% 717
%WC% 718
%WC% 719
%WC% 720
echo.
%WC% 804
%WC% 721
%WC% 722
%WC% 723
echo.
%WC% 100
%WC% 728
%WC% 102
echo.

echo.
%WC% 729
pause >nul

endlocal
exit /b 0

REM ====================================================================
REM Error handlers (goto targets)
REM ====================================================================
:ERR_NODE
%WC% 400
%WC% 732
pause
exit /b 1

:ERR_NPM
%WC% 401
pause
exit /b 1

:ERR_DOCKER
%WC% 402
%WC% 733
pause
exit /b 1

:ERR_DOCKER_START
%WC% 403
pause
exit /b 1

:ERR_COMPOSE
%WC% 404
pause
exit /b 1

:ERR_COMPOSE_FILE
%WC% 405
%WC% 734
pause
exit /b 1

:ERR_BACKEND_BUILD
%WC% 406
pause
exit /b 1

:ERR_BACKEND_UP
%WC% 407
pause
exit /b 1

:ERR_NPM_INSTALL
%WC% 408
%WC% 731
pause
exit /b 1
