export const GOLDEN_SOUP_QUOTES = Object.freeze([
    // [Geek Romantic]
    { category: 'Geek Romantic', cn: '我在变量之间藏了心事，在函数里练习温柔。', en: 'I hide my feelings between variables and practice tenderness in functions.' },
    { category: 'Geek Romantic', cn: '物理说光有路径，我说你有坐标。', en: 'Physics says light has a path; I say you have coordinates.' },
    { category: 'Geek Romantic', cn: '如果宇宙有注释，我想那行一定写着"继续热爱"。', en: 'If the universe had comments, one line would read: keep loving.' },
    { category: 'Geek Romantic', cn: '在离散与连续之间，我选择把你插值成永恒。', en: 'Between discrete and continuous, I interpolate you into eternity.' },
    { category: 'Geek Romantic', cn: '当程序跑通的那一刻，世界短暂地变得诚实。', en: 'The moment the program runs, the world becomes honest for a while.' },
    { category: 'Geek Romantic', cn: '我把想念压进压缩包，解压时全是你。', en: 'I zip up my longing, and when unzipped, it is all you.' },

    // [Humorous Satire]
    { category: 'Humorous Satire', cn: 'Bug 从不下班，它只是换个时间提醒你谦卑。', en: 'Bugs never clock out; they just remind you to stay humble at new hours.' },
    { category: 'Humorous Satire', cn: '我不是修复了问题，我只是把问题移到了别人看不见的地方。', en: 'I did not fix the issue; I moved it where no one can see it.' },
    { category: 'Humorous Satire', cn: '改需求最快的方法：先说"这很简单"。', en: 'The fastest way to trigger requirement changes is to say "this is easy."' },
    { category: 'Humorous Satire', cn: '加班不是热爱，是与未知报错进行深夜谈判。', en: 'Overtime is not passion; it is midnight negotiation with unknown errors.' },
    { category: 'Humorous Satire', cn: '我有两种心情：在修 Bug，和在等下一个 Bug。', en: 'I have two moods: fixing a bug, and waiting for the next one.' },
    { category: 'Humorous Satire', cn: '我的人生就像没写 Readme 的项目，全靠瞎猜。', en: 'My life is like a project without a Readme; it\'s all guesswork.' },
    { category: 'Humorous Satire', cn: '改 Bug 的过程，就是旧问题被新 Bug 完美覆盖的过程。', en: 'Debugging is the process where old issues are perfectly covered by new bugs.' },
    { category: 'Humorous Satire', cn: '生活不仅有诗和远方，还有修不完的生产环境故障。', en: 'Life has poetry and far lands, and endless production environment failures.' },
    { category: 'Humorous Satire', cn: '我的梦想是当个咸鱼，可惜咸鱼也会被拉去加班。', en: 'My dream is to be a salted fish, but even they get dragged into overtime.' },
    { category: 'Humorous Satire', cn: '虽然我的代码很烂，但它跑起来的样子像极了艺术。', en: 'My code is terrible, but the way it runs is pure art.' },
    { category: 'Humorous Satire', cn: '只要我不写代码，我的代码库就是完美的。', en: 'As long as I don\'t write code, my repository is perfect.' },
    { category: 'Humorous Satire', cn: '我的逻辑没问题，有问题的是这个物理世界。', en: 'My logic is fine; it\'s the physical world that has issues.' },
    { category: 'Humorous Satire', cn: '虽然我没钱，但我有一大堆没填的坑和报错。', en: 'I have no money, but I have plenty of technical debt and errors.' },
    { category: 'Humorous Satire', cn: '有些人活着是为了改变世界，我活着是为了按时 commit。', en: 'Some live to change the world; I live to commit on time.' },
    { category: 'Humorous Satire', cn: '生活就像一个糟糕的 IDE，提醒全是红色的。', en: 'Life is like a bad IDE; every reminder is in red.' },
    { category: 'Humorous Satire', cn: '与其担心被 AI 替代，不如担心能不能活到退休。', en: 'Instead of worrying about AI replacement, worry if you\'ll live to retirement.' },
    { category: 'Humorous Satire', cn: '代码可以优雅，但写代码的姿势通常很狼狈。', en: 'Code can be elegant, but the posture while writing it is usually pathetic.' },
    { category: 'Humorous Satire', cn: '我以为我在管理项目，其实是项目在管理我的死期。', en: 'I thought I was managing the project, but the project is managing my deadline.' },

    // [Disillusioned]
    { category: 'Disillusioned', cn: '成年人的崩溃，通常发生在"加载中"。', en: 'Adult breakdown often happens during "loading."' },
    { category: 'Disillusioned', cn: '后来我明白，很多努力只是延迟失败。', en: 'Later I learned many efforts merely delay failure.' },
    { category: 'Disillusioned', cn: '生活像未处理异常，出现时从不提前通知。', en: 'Life is an unhandled exception: it never announces itself.' },
    { category: 'Disillusioned', cn: '我把希望设成常量，现实总在运行时改值。', en: 'I set hope as a constant; reality mutates it at runtime.' },
    { category: 'Disillusioned', cn: '深夜最难的不是问题，是再也不相信答案。', en: 'At night, the hardest thing is not the problem but losing faith in answers.' },
    { category: 'Disillusioned', cn: '看起来我在进步，其实只是更会掩饰疲惫。', en: 'It looks like progress; I just got better at hiding exhaustion.' },
    { category: 'Disillusioned', cn: '梦想没有消失，它只是被账单重命名了。', en: 'Dreams did not disappear; they were renamed as bills.' },
    { category: 'Disillusioned', cn: '我依旧准时起床，只是再也不期待早晨。', en: 'I still wake up on time, I just no longer expect mornings.' },
    { category: 'Disillusioned', cn: '努力像回车键，按下去不一定有回响。', en: 'Effort is like pressing Enter: no guarantee of response.' },
    { category: 'Disillusioned', cn: '有些路走久了，不是到达，是麻木。', en: 'Some long roads lead not to arrival but numbness.' },
    { category: 'Disillusioned', cn: '有些事不是坚持就有结果，比如死掉的链接。', en: 'Some things don\'t yield results through persistence, like dead links.' },
    { category: 'Disillusioned', cn: '世界并没有针对你，它只是根本不在意你。', en: 'The world isn\'t targeting you; it simply doesn\'t care about you at all.' },
    { category: 'Disillusioned', cn: '我们都在等待一个不复存在的备份。', en: 'We are all waiting for a backup that no longer exists.' },
    { category: 'Disillusioned', cn: '所谓的成长，就是学会了给所有的失望打补丁。', en: 'Growth is learning how to patch all your disappointments.' },
    { category: 'Disillusioned', cn: '梦想破灭的声音，还没有键盘敲击声大。', en: 'The sound of dreams shattering is quieter than a keystroke.' },
    { category: 'Disillusioned', cn: '我试过格式化人生，可硬件已经老化了。', en: 'I tried to format my life, but the hardware is already aging.' },
    { category: 'Disillusioned', cn: '别谈未来，现在的我也只是在超负荷运转。', en: 'Don\'t talk about the future; even my current self is running at overload.' },
    { category: 'Disillusioned', cn: '有些报错可以修复，有些遗憾只能归档。', en: 'Some errors can be fixed; some regrets can only be archived.' },
    { category: 'Disillusioned', cn: '原以为自己是主角，结果只是个背景进程。', en: 'I thought I was the main process, but I\'m just a background task.' },
    { category: 'Disillusioned', cn: '时间带走的不仅是青春，还有对报错的耐心。', en: 'Time takes not only youth, but also patience for error messages.' },
    { category: 'Disillusioned', cn: '生活没有撤销键，只有不停增加的 Readonly。', en: 'Life has no Undo; only ever-increasing Readonly status.' },
    { category: 'Disillusioned', cn: '所谓的避风港，不过是延迟了风暴的到达。', en: 'A safe harbor merely delays the arrival of the storm.' },
    { category: 'Disillusioned', cn: '我们终将变成自己曾经最讨厌的那种代码。', en: 'We will eventually become the kind of code we once hated most.' },
    { category: 'Disillusioned', cn: '希望是消耗品，而我早已透支。', en: 'Hope is a consumable, and I am long since overdrawn.' },
    { category: 'Disillusioned', cn: '看窗外的天黑了又亮，代码还是原来的模样。', en: 'Watching the sky turn dark then bright; the code remains unchanged.' },
    { category: 'Disillusioned', cn: '所谓的诗和远方，都被困在了 15 寸的屏幕里。', en: 'What we call poetry and far lands are trapped in a 15-inch screen.' },
    { category: 'Disillusioned', cn: '有些努力只是为了证明：我真的不行。', en: 'Some efforts only serve to prove: I really can\'t do it.' },
    { category: 'Disillusioned', cn: '在这个充满随机性的世界里，稳定才是一种错觉。', en: 'In this world full of randomness, stability is the true illusion.' },
    { category: 'Disillusioned', cn: '所谓的救赎，不过是换了一个更舒适的牢笼。', en: 'What we call redemption is just switching to a more comfortable cage.' },
    { category: 'Disillusioned', cn: '我以为我在追逐梦想，结果只是被它牵着走。', en: 'I thought I was chasing dreams, but I was just being led by them.' },
    { category: 'Disillusioned', cn: '有些人不是不努力，而是努力了也没用。', en: 'Some people are not unmotivated; they just put effort into things that don\'t work.' },
    { category: 'Disillusioned', cn: '我以为时间会治愈一切，结果只是让一切变得麻木。', en: 'I thought time would heal everything, but it just makes everything numb.' },
    { category: 'Disillusioned', cn: '生活没有彩蛋，只有不断出现的隐藏 Bug。', en: 'Life has no Easter eggs, only continuously emerging hidden bugs.' },
    { category: 'Disillusioned', cn: '所谓的坚持，不过是对失败的习惯性容忍。', en: 'What we call persistence is just habitual tolerance for failure.' },
    { category: 'Disillusioned', cn: '我学会了微笑，因为解释没有预算', en: 'I learned to smile because explanations have no budget.' },
    { category: 'Disillusioned', cn: '有些人不是不在意你，而是根本没有把你放在心上。', en: 'Some people don\'t not care about you; they just never put you in their heart at all.' },
    { category: 'Disillusioned', cn: '我以为我在创造未来，结果只是被时代淘汰了。', en: 'I thought I was creating the future, but I was just being eliminated by the times.' },
    { category: 'Disillusioned', cn: '有些人不是不爱了，而是根本没爱过。', en: 'Some people don\'t stop loving; they just never loved in the first place.' },
    { category: 'Disillusioned', cn: '我以为我在追求自由，结果只是被另一个牢笼锁住了。', en: 'I thought I was pursuing freedom, but I was just locked in another cage.' },
    { category: 'Disillusioned', cn: '有些人不是不重要，而是根本没有存在过。', en: 'Some people are not unimportant; they just never existed at all.' },
    { category: 'Disillusioned', cn: '我以为我在寻找意义，结果只是被无意义淹没了。', en: 'I thought I was searching for meaning, but I was just drowned in meaninglessness.' },
    { category: 'Disillusioned', cn: '有些人不是不珍惜你，而是根本没有把你当回事。', en: 'Some people don\'t not cherish you; they just never took you seriously at all.' },
    { category: 'Disillusioned', cn: '我以为我在追逐梦想，结果只是被现实追着跑了。', en: 'I thought I was chasing dreams, but I was just being chased by reality.' },
    { category: 'Disillusioned', cn: '你以为别人赢在天赋，其实他们只是比你更早接受了现实。', en: 'You think others win by talent; they just accepted reality earlier than you did.' },
    { category: 'Disillusioned', cn: '努力不会骗人，但努力的方向会。', en: 'Effort doesn’t lie, but the direction of effort does.' },
    { category: 'Disillusioned', cn: '你以为是起点不公平，其实是终点根本不等你。', en: 'You think the start is unfair; the truth is the finish line isn’t waiting for you.' },
    { category: 'Disillusioned', cn: '失败不可怕，可怕的是你连失败的资格都没有。', en: 'Failure isn’t scary; not even qualifying to fail is.' },
    { category: 'Disillusioned', cn: '你不是不优秀，只是你的优秀没人需要。', en: 'You’re not incapable; your capability just isn’t needed.' },
    { category: 'Disillusioned', cn: '世界不是不公平，而是根本没打算公平。', en: 'The world isn’t unfair; it was never meant to be fair.' },
    { category: 'Disillusioned', cn: '你以为你在选择，其实只是被筛选。', en: 'You think you’re choosing; you’re just being filtered.' },
    { category: 'Disillusioned', cn: '有些门不是没敲开，是从一开始就没给你钥匙。', en: 'Some doors weren’t unopened; you were never given a key.' },
    { category: 'Disillusioned', cn: '你以为是运气不好，其实是实力刚好不够。', en: 'You call it bad luck; it’s just not enough skill.' },
    { category: 'Disillusioned', cn: '所谓机会，只是留给已经准备好的人筛掉你的借口。', en: 'Opportunity is just a polite way to eliminate the unprepared.' },
    { category: 'Disillusioned', cn: '你拼命追赶的东西，别人一出生就拥有。', en: 'What you chase desperately, others are born with.' },
    { category: 'Disillusioned', cn: '不是你不够努力，是你努力的速度追不上差距的扩大。', en: 'It’s not lack of effort; it’s that the gap widens faster than you close it.' },
    { category: 'Disillusioned', cn: '你以为你在坚持，其实你只是在拖延失败。', en: 'You think you’re persisting; you’re just delaying failure.' },
    { category: 'Disillusioned', cn: '你不是看不懂规则，是规则根本不需要你。', en: 'It’s not that you don’t understand the rules; the rules don’t need you.' },
    { category: 'Disillusioned', cn: '你以为你在成长，其实只是换了一种方式重复。', en: 'You think you’re growing; you’re just repeating differently.' },
    { category: 'Disillusioned', cn: '有些路不是难走，是走了也没用。', en: 'Some paths aren’t hard; they’re useless.' },
    { category: 'Disillusioned', cn: '你以为你在逆袭，其实只是还没被淘汰。', en: 'You think it’s a comeback; you just haven’t been eliminated yet.' },
    { category: 'Disillusioned', cn: '你羡慕的不是成功，是成功背后的资源。', en: 'You don’t envy success; you envy the resources behind it.' },
    { category: 'Disillusioned', cn: '你努力的极限，只是别人起点的下限。', en: 'Your limit is someone else’s starting floor.' },
    { category: 'Disillusioned', cn: '你不是没机会，是机会不属于你。', en: 'It’s not lack of chances; they just aren’t yours.' },
    { category: 'Disillusioned', cn: '你以为人脉重要，其实是你不重要。', en: 'You think connections matter; it’s that you don’t.' },
    { category: 'Disillusioned', cn: '你以为别人冷漠，其实只是你不值得热情。', en: 'You see coldness; they just don’t find you worth warmth.' },
    { category: 'Disillusioned', cn: '你不是被忽视，是被看透了。', en: 'You’re not ignored; you’re seen through.' },
    { category: 'Disillusioned', cn: '你以为关系淡了，其实从来没浓过。', en: 'You think it faded; it was never strong.' },
    { category: 'Disillusioned', cn: '你不是不合群，是没有被群体需要。', en: 'You’re not antisocial; you’re unnecessary.' },
    { category: 'Disillusioned', cn: '你以为别人变了，其实只是你终于看清了。', en: 'They didn’t change; you finally saw clearly.' },
    { category: 'Disillusioned', cn: '你以为是误会，其实是判断正确。', en: 'You call it misunderstanding; it’s accurate judgment.' },
    { category: 'Disillusioned', cn: '你以为你重要，是因为没人告诉你真相。', en: 'You feel important because no one told you the truth.' },
    { category: 'Disillusioned', cn: '你以为有人在等你，其实大家都在赶路。', en: 'You think someone waits; everyone’s just moving on.' },
    { category: 'Disillusioned', cn: '你不是被放弃，是从未被选择。', en: 'You weren’t abandoned; you were never chosen.' },
    { category: 'Disillusioned', cn: '你以为未来可期，其实只是时间在流逝。', en: 'You think the future is promising; it’s just time passing.' },
    { category: 'Disillusioned', cn: '你以为在积累，其实在消耗。', en: 'You think you’re building; you’re draining.' },
    { category: 'Disillusioned', cn: '你以为稳定，其实是停滞。', en: 'You call it stability; it’s stagnation.' },
    { category: 'Disillusioned', cn: '你以为风险大，其实是收益小。', en: 'You fear risk; the real issue is low return.' },
    { category: 'Disillusioned', cn: '你以为安全，其实只是没有选择。', en: 'You think it’s safe; you just lack options.' },
    { category: 'Disillusioned', cn: '你以为是在等待，其实是在浪费。', en: 'You think you’re waiting; you’re wasting.' },
    { category: 'Disillusioned', cn: '你以为是在规划，其实是在逃避。', en: 'You think you’re planning; you’re avoiding.' },
    { category: 'Disillusioned', cn: '你以为你慢慢来，其实你已经掉队了。', en: 'You think you’re taking it slow; you’ve already fallen behind.' },
    { category: 'Disillusioned', cn: '你以为是低谷，其实是常态。', en: 'You call it a low point; it’s the baseline.' },
    { category: 'Disillusioned', cn: '你以为会变好，其实只是习惯了不好。', en: 'You expect improvement; you just adapt to worse.' },
    { category: 'Disillusioned', cn: '你以为选择很多，其实都不是你的。', en: 'You think you have options; none are yours.' },
    { category: 'Disillusioned', cn: '你以为你在试错，其实在重复错误。', en: 'You think you’re experimenting; you’re repeating mistakes.' },
    { category: 'Disillusioned', cn: '你以为你在改变，其实只是换个姿势失败。', en: 'You think you’re changing; you’re failing differently.' },
    { category: 'Disillusioned', cn: '你以为你在坚持梦想，其实梦想早就放弃你了。', en: 'You hold onto dreams; they’ve let go of you.' },
    { category: 'Disillusioned', cn: '你以为你在突破，其实只是突破不了。', en: 'You think it’s a breakthrough; it’s a dead end.' },
    { category: 'Disillusioned', cn: '你以为你特别，其实只是普通得刚刚好。', en: 'You feel special; you’re perfectly average.' },
    { category: 'Disillusioned', cn: '你以为你清醒，其实只是更绝望。', en: 'You think you’re aware; you’re just more hopeless.' },
    { category: 'Disillusioned', cn: '你以为你努力过，其实只是努力过一阵。', en: 'You think you tried; you tried briefly.' },
    { category: 'Disillusioned', cn: '你以为差一点，其实差很多。', en: 'You think it’s close; it’s far off.' },
    { category: 'Disillusioned', cn: '你以为运气不好，其实概率就是这样。', en: 'You blame luck; it’s just probability.' },
    { category: 'Disillusioned', cn: '你以为别人不理解你，其实没人想理解。', en: 'You feel misunderstood; no one’s interested.' },
    { category: 'Disillusioned', cn: '你以为你很累，其实只是效率低。', en: 'You feel tired; it’s inefficiency.' },
    { category: 'Disillusioned', cn: '你以为别人优秀，其实他们只是没停下来。', en: 'Others aren’t superior; they just didn’t stop.' },
    { category: 'Disillusioned', cn: '你以为你晚一点也行，其实窗口早关了。', en: 'You think later works; the window closed.' },
    { category: 'Disillusioned', cn: '你以为你在努力活着，其实只是被动存在。', en: 'You think you’re living; you’re just existing.' },
    { category: 'Disillusioned', cn: '你以为你在抗争，其实你在消耗自己。', en: 'You think you’re resisting; you’re draining yourself.' },
    { category: 'Disillusioned', cn: '你以为你在看清世界，其实世界早看清你了。', en: 'You think you see the world; it sees you clearly.' },
    { category: 'Disillusioned', cn: '你以为你在前进，其实只是没停下。', en: 'You think you’re moving forward; you just haven’t stopped.' },
    { category: 'Disillusioned', cn: '你以为你还能翻盘，其实筹码早没了。', en: 'You expect a comeback; you’re out of chips.' },
    { category: 'Disillusioned', cn: '你以为人生有剧情，其实只是随机生成。', en: 'You expect a plot; it’s procedurally generated.' },
    { category: 'Disillusioned', cn: '你以为你在对抗命运，其实你在执行它。', en: 'You think you fight fate; you execute it.' },
    { category: 'Disillusioned', cn: '你以为你在创造意义，其实只是填补空白。', en: 'You think you create meaning; you fill a void.' },
    { category: 'Disillusioned', cn: '你以为你重要，是因为系统还没清理你。', en: 'You feel important; the system hasn’t cleaned you up yet.' },
    { category: 'Disillusioned', cn: '你以为失败有意义，其实只是结果。', en: 'You assign meaning to failure; it’s just an outcome.' },
    { category: 'Disillusioned', cn: '你以为你能控制，其实只是参与。', en: 'You think you control; you just participate.' },
    { category: 'Disillusioned', cn: '你以为你在选择生活，其实生活在选择你。', en: 'You choose life; life chooses you.' },
    { category: 'Disillusioned', cn: '你以为你在改变世界，其实世界在改变你。', en: 'You change the world; it changes you.' },
    { category: 'Disillusioned', cn: '你以为你在避免错误，其实只是减少尝试。', en: 'You avoid mistakes; you reduce attempts.' },
    { category: 'Disillusioned', cn: '你以为你还有时间，其实时间从来不属于你。', en: 'You think you have time; you never owned it.' },
    { category: 'Disillusioned', cn: '你以为终点在前方，其实你一直在原地。', en: 'You see a finish line ahead; you’re standing still.' },
    { category: 'Disillusioned', cn: '努力不一定有回报，但不努力，一定很轻松。', en: 'Effort doesn\'t necessarily bring rewards, but not trying is definitely easy.' },
    { category: 'Disillusioned', cn: '你拼尽全力的上限，不过是别人的起点。', en: 'The upper limit of your best efforts is just the starting point of others.' },
    { category: 'Disillusioned', cn: '时间不是解药，是麻药，醒了之后，疼得更狠。', en: 'Time is not an antidote, but an anesthetic; when you wake up, it hurts even more.' },
    { category: 'Disillusioned', cn: '所谓希望，不过是让你多熬一会儿的谎言。', en: 'The so-called hope is just a lie that makes you endure a little longer.' },
    { category: 'Disillusioned', cn: '你以为的逆袭，不过是命运偶尔的施舍，转瞬即逝。', en: 'The counterattack you think is just an occasional alms from fate, fleeting.' },
    { category: 'Disillusioned', cn: '善良没用，你得漂亮，得有钱，得够狠。', en: 'Kindness is useless; you have to be beautiful, rich, and ruthless enough.' },
    { category: 'Disillusioned', cn: '有些人努力，是为了活着；有些人活着，不用努力。', en: 'Some people work hard just to live; some people live without having to work hard.' },
    { category: 'Disillusioned', cn: '我以为熬过去就好了，没想到熬过去，还有更难的。', en: 'I thought getting through it would be okay, but I didn\'t expect that after getting through it, there would be harder things.' },
    { category: 'Disillusioned', cn: '生活的真相：你越想要什么，就越得不到什么。', en: 'The truth of life: the more you want something, the more you can\'t get it.' },
    { category: 'Disillusioned', cn: '所谓成长，就是从满怀期待，变成麻木不仁。', en: 'The so-called growth is from full of expectations to numbness.' },
    { category: 'Disillusioned', cn: '你掏心掏肺对待的人，正在背后笑话你的天真。', en: 'The person you treat wholeheartedly is laughing at your naivety behind your back.' },
    { category: 'Disillusioned', cn: '努力改变命运，不过是安慰底层人的自我欺骗。', en: 'Working hard to change fate is just self-deception to comfort people at the bottom.' },
    { category: 'Disillusioned', cn: '我以为我很特别，原来只是芸芸众生里，最普通的炮灰。', en: 'I thought I was special, but it turns out I\'m just the most ordinary cannon fodder among all living beings.' },
    { category: 'Disillusioned', cn: '承诺都是用来打破的，深情都是用来辜负的。', en: 'Promises are all meant to be broken, and deep affection is all meant to be let down.' },
    { category: 'Disillusioned', cn: '你越懂事，越没人疼；越迁就，越受委屈。', en: 'The more sensible you are, the less someone cares about you; the more you accommodate, the more wronged you are.' },
    { category: 'Disillusioned', cn: '生活没有退路，只有绝路，要么熬，要么死。', en: 'Life has no retreat, only a dead end; either endure or die.' },
    { category: 'Disillusioned', cn: '有些人不是不优秀，是优秀错了地方，一文不值。', en: 'Some people are not unexcellent; they are excellent in the wrong place, worth nothing.' },
    { category: 'Disillusioned', cn: '我以为坚持就能看到光，结果只看到了无尽的黑暗。', en: 'I thought persistence would let me see the light, but I only saw endless darkness.' },
    { category: 'Disillusioned', cn: '所谓公平，就是强者制定规则，弱者被迫服从。', en: 'The so-called fairness is that the strong make the rules, and the weak are forced to obey.' },
    { category: 'Disillusioned', cn: '你付出的所有真心，最后都变成了别人的笑话。', en: 'All the sincerity you gave finally turned into a joke of others.' },
    { category: 'Disillusioned', cn: '努力的意义，就是让你知道，有些事，再努力也没用。', en: 'The meaning of effort is to let you know that some things are useless no matter how hard you try.' },
    { category: 'Disillusioned', cn: '我以为时间会让我忘记，结果只是让我习惯了痛苦。', en: 'I thought time would make me forget, but it just made me get used to the pain.' },
    { category: 'Disillusioned', cn: '生活的Bug从来不会修复，只会越积越多，压垮你。', en: 'Life\'s bugs are never fixed; they only accumulate more and more, crushing you.' },
    { category: 'Disillusioned', cn: '所谓的幸运，不过是别人不屑一顾的剩余。', en: 'The so-called luck is just the leftover that others disdain.' },
    { category: 'Disillusioned', cn: '你越是挣扎，就越被生活捆得越紧。', en: 'The more you struggle, the tighter life binds you.' },
    { category: 'Disillusioned', cn: '有些人不是没能力，是没机会，而机会，从来不属于普通人。', en: 'Some people are not incompetent; they just have no chance, and chances never belong to ordinary people.' },
    { category: 'Disillusioned', cn: '我以为我在拯救自己，结果只是把自己推向更深的深渊。', en: 'I thought I was saving myself, but I was just pushing myself into a deeper abyss.' },
    { category: 'Disillusioned', cn: '深情一文不值，新鲜感才是成年人的通行证。', en: 'Deep affection is worthless; freshness is the pass for adults.' },
    { category: 'Disillusioned', cn: '你拼尽全力去迎合，最后还是活成了别人不喜欢的样子。', en: 'You try your best to cater, but in the end, you still live like someone others don\'t like.' },
    { category: 'Disillusioned', cn: '生活没有奇迹，只有你自欺欺人的侥幸。', en: 'There are no miracles in life, only your self-deceptive fluke.' },
    { category: 'Disillusioned', cn: '所谓的懂事，就是压抑自己的情绪，成全别人的舒服。', en: 'The so-called sensible is to suppress your own emotions to make others comfortable.' },
    { category: 'Disillusioned', cn: '努力了一辈子，最后发现，不过是为别人做了嫁衣。', en: 'After working hard all your life, you finally find that you are just making wedding clothes for others.' },
    { category: 'Disillusioned', cn: '我以为我能改变世界，结果连自己都改变不了。', en: 'I thought I could change the world, but I couldn\'t even change myself.' },
    { category: 'Disillusioned', cn: '有些人不是不珍惜，是根本不懂什么叫珍惜，也不想懂。', en: 'Some people don\'t not cherish; they just don\'t understand what cherishing is, and don\'t want to understand.' },
    { category: 'Disillusioned', cn: '自由从来都是奢侈品，你连喘息的资格都没有，何谈自由。', en: 'Freedom has always been a luxury; you don\'t even have the right to breathe, let alone freedom.' },
    { category: 'Disillusioned', cn: '你越善良，越容易被欺负；越真诚，越容易被伤害。', en: 'The kinder you are, the easier you are to be bullied; the more sincere you are, the easier you are to be hurt.' },
    { category: 'Disillusioned', cn: '生活的真相：不是你不够好，是你再好，也没人在意。', en: 'The truth of life: it\'s not that you\'re not good enough, but no one cares how good you are.' },
    { category: 'Disillusioned', cn: '所谓的梦想，不过是让你在底层挣扎时，多一个借口。', en: 'The so-called dream is just an excuse for you to struggle at the bottom.' },
    { category: 'Disillusioned', cn: '我以为熬到终点就有惊喜，结果终点只有绝望在等我。', en: 'I thought there would be a surprise when I reached the end, but only despair was waiting for me at the end.' },
    { category: 'Disillusioned', cn: '有些人不是不努力，是努力的方向，从一开始就错了。', en: 'Some people are not unmotivated; the direction of their efforts was wrong from the beginning.' },
    { category: 'Disillusioned', cn: '你付出的所有努力，都抵不过别人一句“我有关系”。', en: 'All the efforts you put in are not worth others saying "I have connections".' },
    { category: 'Disillusioned', cn: '时间不会治愈你，只会让你习惯，习惯被伤害，习惯不被爱。', en: 'Time won\'t heal you; it will only make you get used to being hurt and not being loved.' },
    { category: 'Disillusioned', cn: '所谓的朋友，不过是你有用时靠近，你没用时远离。', en: 'The so-called friends are just people who approach you when you are useful and stay away when you are not.' },
    { category: 'Disillusioned', cn: '你越想抓住什么，就越容易失去什么，无一例外。', en: 'The more you want to hold on to something, the easier it is to lose it, without exception.' },
    { category: 'Disillusioned', cn: '努力的意义，就是证明自己，真的不行。', en: 'The meaning of effort is to prove that you really can\'t do it.' },
    { category: 'Disillusioned', cn: '我以为我很坚强，原来只是没经历过真正的绝望。', en: 'I thought I was strong, but it turns out I just haven\'t experienced real despair.' },
    { category: 'Disillusioned', cn: '生活没有偏爱，只有偏爱那些不需要偏爱的人。', en: 'Life has no preference; it only favors those who don\'t need preference.' },
    { category: 'Disillusioned', cn: '有些人不是不爱，是爱不起，也配不上。', en: 'Some people don\'t stop loving; they can\'t afford to love, and don\'t deserve it.' },
    { category: 'Disillusioned', cn: '你掏心掏肺的付出，最后换来的，都是得寸进尺。', en: 'All the wholehearted efforts you give will eventually be met with greed.' },
    { category: 'Disillusioned', cn: '所谓的成长，就是把哭声调成静音，把情绪藏进心底。', en: 'The so-called growth is to turn the cry to silent and hide emotions in the bottom of the heart.' },
    { category: 'Disillusioned', cn: '我以为我能逃离，结果只是从一个火坑，跳进另一个火坑。', en: 'I thought I could escape, but I just jumped from one pit of fire to another.' },
    { category: 'Disillusioned', cn: '努力不一定能成功，但不努力，一定不会失败，因为你连失败的资格都没有。', en: 'Effort doesn\'t necessarily lead to success, but not trying will definitely not lead to failure, because you don\'t even have the right to fail.' },
    { category: 'Disillusioned', cn: '生活的Bug，从来不会眷顾任何人，你越弱小，它越嚣张。', en: 'Life\'s bugs never favor anyone; the weaker you are, the more arrogant they are.' },
    { category: 'Disillusioned', cn: '有些人不是不明白，是明白太晚，一切都无法挽回。', en: 'Some people are not ununderstanding; they understand too late, and everything is irreversible.' },
    { category: 'Disillusioned', cn: '你以为的希望，不过是命运给你画的大饼，永远吃不到。', en: 'The hope you think is just a pie drawn by fate, which you will never eat.' },
    { category: 'Disillusioned', cn: '所谓的公平，不过是弱者的自我安慰，强者的游戏规则。', en: 'The so-called fairness is just self-consolation for the weak and a game rule for the strong.' },
    { category: 'Disillusioned', cn: '我以为时间会给我答案，结果时间只给了我更多的疑问。', en: 'I thought time would give me answers, but time only gave me more questions.' },
    { category: 'Disillusioned', cn: '你越努力，越发现，自己不过是别人棋盘上的一颗棋子。', en: 'The harder you work, the more you find that you are just a chess piece on others\' chessboard.' },
    { category: 'Disillusioned', cn: '善良是软肋，真诚是枷锁，越善良，越难前行。', en: 'Kindness is a weakness, sincerity is a shackle; the kinder you are, the harder it is to move forward.' },
    { category: 'Disillusioned', cn: '有些人不是不努力，是努力了，也赶不上别人的与生俱来。', en: 'Some people are not unmotivated; even if they work hard, they can\'t catch up with others\' inborn advantages.' },
    { category: 'Disillusioned', cn: '生活没有惊喜，只有惊吓，一次比一次狠。', en: 'There are no surprises in life, only scares, getting worse every time.' },
    { category: 'Disillusoned', cn: '所谓的坚持，不过是不甘心，不甘心自己的努力白费。', en: 'The so-called persistence is just unwillingness, unwillingness that your efforts are in vain.' },
    { category: 'Disillusioned', cn: '我以为我能改变别人，结果只是被别人改变，变得面目全非。', en: 'I thought I could change others, but I was just changed by others, becoming unrecognizable.' },
    { category: 'Disillusioned', cn: '你越迁就别人，别人就越不把你当回事，这是人性。', en: 'The more you accommodate others, the less they take you seriously; this is human nature.' },
    { category: 'Disillusioned', cn: '努力的意义，就是让你看清现实，现实有多残酷，你就有多渺小。', en: 'The meaning of effort is to let you see the reality clearly; the crueler the reality, the smaller you are.' },
    { category: 'Disillusioned', cn: '时间不是解药，是毒药，慢慢侵蚀你所有的期待。', en: 'Time is not an antidote, but a poison, slowly eroding all your expectations.' },
    { category: 'Disillusioned', cn: '有些人不是不珍惜，是珍惜的不是你，从来都不是。', en: 'Some people don\'t not cherish; what they cherish is not you, never you.' },
    { category: 'Disillusioned', cn: '你以为的自由，不过是别人施舍的怜悯，随时可以收回。', en: 'The freedom you think is just the mercy given by others, which can be taken back at any time.' },
    { category: 'Disillusioned', cn: '生活的真相：你越想变好，就越难变好，阻碍从来不会缺席。', en: 'The truth of life: the more you want to get better, the harder it is to get better; obstacles will never be absent.' },
    { category: 'Disillusioned', cn: '所谓的梦想，不过是你逃避现实的借口，自欺欺人罢了。', en: 'The so-called dream is just an excuse for you to escape reality, self-deception.' },
    { category: 'Disillusioned', cn: '我以为熬过去就是晴天，结果熬过去，还是阴雨天。', en: 'I thought getting through it would be sunny, but after getting through it, it\'s still rainy.' },
    { category: 'Disillusioned', cn: '有些人不是不努力，是努力错了对象，竹篮打水一场空。', en: 'Some people are not unmotivated; they worked hard on the wrong target, getting nothing in the end.' },
    { category: 'Disillusioned', cn: '你付出的所有真心，都被当成理所当然，一文不值。', en: 'All the sincerity you gave is taken for granted, worth nothing.' },
    { category: 'Disillusioned', cn: '所谓的朋友，不过是利益的结合体，没有利益，寸步难行。', en: 'The so-called friends are just a combination of interests; without interests, it\'s impossible to move forward.' },
    { category: 'Disillusioned', cn: '你越坚强，越没人疼；越脆弱，越没人管，这就是现实。', en: 'The stronger you are, the less someone cares about you; the more vulnerable you are, the less someone cares about you. This is reality.' },
    { category: 'Disillusioned', cn: '努力不一定能改变命运，但能让你更清楚地认识到，命运早已注定。', en: 'Effort doesn\'t necessarily change fate, but it can make you more clearly realize that fate is already destined.' },
    { category: 'Disillusioned', cn: '我以为我能拥有一切，结果连一无所有，都成了奢望。', en: 'I thought I could have everything, but even having nothing has become a luxury.' },
    { category: 'Disillusioned', cn: '生活没有退路，你只能硬着头皮往前走，哪怕前方是悬崖。', en: 'Life has no retreat; you can only move forward bravely, even if there is a cliff ahead.' },
    { category: 'Disillusioned', cn: '有些人不是不优秀，是优秀得不合时宜，被世界抛弃。', en: 'Some people are not unexcellent; they are excellent at the wrong time, abandoned by the world.' },
    { category: 'Disillusioned', cn: '所谓的成长，就是学会接受，接受自己的平庸，接受现实的残酷。', en: 'The so-called growth is to learn to accept, accept your own mediocrity, and accept the cruelty of reality.' },
    { category: 'Disillusioned', cn: '你越想抓住幸福，幸福就越容易溜走，就像沙握在手里。', en: 'The more you want to hold happiness, the easier it is to slip away, just like sand in your hand.' },
    { category: 'Disillusioned', cn: '努力的意义，就是让你知道，有些差距，永远无法弥补。', en: 'The meaning of effort is to let you know that some gaps can never be made up.' },
    { category: 'Disillusioned', cn: '我以为时间会抚平伤口，结果伤口只是结了痂，一碰就疼。', en: 'I thought time would heal the wound, but the wound only scabbed and hurts when touched.' },
    { category: 'Disillusioned', cn: '生活的Bug，从来不会给你修复的机会，只会让你一错再错。', en: 'Life\'s bugs never give you a chance to fix them; they only make you make mistakes again and again.' },
    { category: 'Disillusioned', cn: '有些人不是不珍惜，是他们的珍惜，太廉价，一文不值。', en: 'Some people don\'t not cherish; their cherishing is too cheap, worth nothing.' },
    { category: 'Disillusioned', cn: '你以为的逆袭，不过是命运的玩笑，笑完之后，还是原地踏步。', en: 'The counterattack you think is just a joke of fate; after laughing, you still stay in place.' },
    { category: 'Disillusioned', cn: '所谓的公平，就是你努力十年，不如别人出生就拥有。', en: 'The so-called fairness is that you work hard for ten years, not as good as what others have at birth.' },
    { category: 'Disillusioned', cn: '我以为我能逃离孤独，结果孤独就像影子，形影不离。', en: 'I thought I could escape loneliness, but loneliness is like a shadow, never leaving.' },
    { category: 'Disillusioned', cn: '你越善良，越容易被利用；越真诚，越容易被背叛。', en: 'The kinder you are, the easier you are to be used; the more sincere you are, the easier you are to be betrayed.' },
    { category: 'Disillusioned', cn: '生活没有奇迹，只有你自欺欺人的自我安慰。', en: 'There are no miracles in life, only your self-deceptive self-consolation.' },
    { category: 'Disillusioned', cn: '所谓的梦想，不过是你年轻时的幻想，长大后，只剩无奈。', en: 'The so-called dream is just your fantasy when you are young; when you grow up, only helplessness remains.' },
    { category: 'Disillusioned', cn: '我以为熬到尽头就有希望，结果尽头，还是无尽的煎熬。', en: 'I thought there would be hope at the end, but the end is still endless suffering.' },
    { category: 'Disillusioned', cn: '有些人不是不努力，是努力了，也得不到别人的认可。', en: 'Some people are not unmotivated; even if they work hard, they can\'t get others\' recognition.' },
    { category: 'Disillusioned', cn: '你付出的所有努力，都抵不过别人的一句敷衍。', en: 'All the efforts you put in are not worth others\' perfunctory words.' },
    { category: 'Disillusioned', cn: '时间不会让你忘记痛苦，只会让你麻木，麻木到感觉不到痛苦。', en: 'Time won\'t make you forget the pain; it will only make you numb, so numb that you can\'t feel the pain.' },
    { category: 'Disillusioned', cn: '所谓的朋友，不过是你需要时不在，你不需要时出现。', en: 'The so-called friends are just people who are not there when you need them, but appear when you don\'t.' },
    { category: 'Disillusioned', cn: '你越迁就，越卑微；越卑微，越被轻视，这就是人性的真相。', en: 'The more you accommodate, the more humble you are; the more humble you are, the more you are despised. This is the truth of human nature.' },
    { category: 'Disillusioned', cn: '努力的意义，就是让你看清自己，看清自己有多渺小，有多无力。', en: 'The meaning of effort is to let you see yourself clearly, see how small and powerless you are.' },
    { category: 'Disillusioned', cn: '我以为我能改变生活，结果生活改变了我，变得我都不认识自己。', en: 'I thought I could change life, but life changed me, making me unrecognizable to myself.' },
    { category: 'Disillusioned', cn: '生活没有彩蛋，只有不断的意外，一次比一次残酷。', en: 'Life has no Easter eggs, only constant accidents, getting crueler every time.' },
    { category: 'Disillusioned', cn: '有些人不是不珍惜，是他们根本不知道，什么是值得珍惜的。', en: 'Some people don\'t not cherish; they just don\'t know what is worth cherishing.' },
    { category: 'Disillusioned', cn: '你以为的自由，不过是你自我欺骗的假象，根本不存在。', en: 'The freedom you think is just an illusion of your self-deception; it doesn\'t exist at all.' },
    { category: 'Disillusioned', cn: '所谓的成长，就是把所有的情绪，都藏在心底，笑着说没事。', en: 'The so-called growth is to hide all emotions in the bottom of the heart and smile and say it\'s okay.' },
    { category: 'Disillusioned', cn: '我以为我能拥有幸福，结果幸福从来都不属于我，从未属于过。', en: 'I thought I could have happiness, but happiness has never belonged to me, never.' },
    { category: 'Disillusioned', cn: '生活的真相：你越努力，越不幸；越平凡，越安稳，却越不甘。', en: 'The truth of life: the harder you work, the more unfortunate you are; the more ordinary you are, the more stable you are, but the more unwilling you are.' },
    { category: 'Disillusioned', cn: '有些人不是不努力，是努力的尽头，还是一无所有。', en: 'Some people are not unmotivated; the end of their efforts is still nothing.' },
    { category: 'Disillusioned', cn: '你掏心掏肺的对待，最后换来的，都是背叛和伤害。', en: 'All the wholehearted treatment you give will eventually be met with betrayal and hurt.' },
    { category: 'Disillusioned', cn: '所谓的希望，不过是让你多熬一会儿，多受一会儿苦。', en: 'The so-called hope is just to let you endure a little longer and suffer a little more.' },
    { category: 'Disillusioned', cn: '我以为时间会给我公平，结果时间只给了我不公，一次又一次。', en: 'I thought time would give me fairness, but time only gave me injustice, again and again.' },
    { category: 'Disillusioned', cn: '生活没有退路，只有往前走，哪怕前方是万丈深渊，也别无选择。', en: 'Life has no retreat; you can only move forward, even if there is an abyss ahead, you have no choice.' },

    // [Deeply Relatable]
    //   { category: 'Deeply Relatable', cn: '地铁很挤，心事更挤。', en: 'The subway is crowded, and so are my thoughts.' },
    { category: 'Deeply Relatable', cn: '朋友圈很热闹，晚饭还是一个人。', en: 'The feed is lively, but dinner is still alone.' },
    { category: 'Deeply Relatable', cn: '我并不脆弱，只是太久没有被好好理解。', en: 'I am not fragile; I have just gone too long without being understood.' },
    { category: 'Deeply Relatable', cn: '很多沉默，不是冷漠，是怕打扰。', en: 'Much silence is not indifference; it is fear of disturbing others.' },
    { category: 'Deeply Relatable', cn: '下班路上风很大，吹不散明天。', en: 'The wind after work is strong, but it cannot blow away tomorrow.' },
    { category: 'Deeply Relatable', cn: '成年人的体面，是把眼泪换成已读不回。', en: 'Adult composure is replacing tears with a seen-but-no-reply.' },
    { category: 'Deeply Relatable', cn: '有些疲惫，不是睡一觉能恢复。', en: 'Some fatigue cannot be fixed by sleep.' },
    { category: 'Deeply Relatable', cn: '在城市里久了，连崩溃都学会静音。', en: 'After long in the city, even breakdowns learn to stay muted.' },
    { category: 'Deeply Relatable', cn: '我把委屈写进备忘录，再删掉。', en: 'I write my grievances in notes, then delete them.' },
    { category: 'Deeply Relatable', cn: '最怕空气突然安静，和控制台突然变红。', en: 'I fear sudden silence, and the console suddenly turning red.' },
    { category: 'Deeply Relatable', cn: '那些没熬过去的夜，最后都写在了发际线上。', en: 'The nights I couldn\'t endure are eventually written on my hairline.' },
    { category: 'Deeply Relatable', cn: '成年人的孤独，是连个能一起改 Bug 的人都没有。', en: 'Adult loneliness is not having a single person to debug with.' },
    { category: 'Deeply Relatable', cn: '我把快乐藏在分号里，可没人注意到我的停顿。', en: 'I hide my joy in semicolons, but no one notices my pauses.' },
    { category: 'Deeply Relatable', cn: '所有的坚强，不过是还没遇到那个能让我软弱的 Bug。', en: 'All strength is just not having met the bug that makes me weak yet.' },
    { category: 'Deeply Relatable', cn: '在这个城市，我的地址总在变，我的孤独却很稳定。', en: 'In this city, my address keeps changing; my loneliness remains stable.' },
    { category: 'Deeply Relatable', cn: '我习惯了等待加载，也习惯了等一个不会来的回复。', en: 'I\'m used to waiting for loading, and for a reply that won\'t come.' },
    { category: 'Deeply Relatable', cn: '所谓的体面，是即使崩溃也要先把代码格式化。', en: 'Composure is formatting your code even while having a breakdown.' },
    { category: 'Deeply Relatable', cn: '谁心里没点伤？只是我把它封装得比较好。', en: 'Who doesn\'t have wounds? I just encapsulated mine well.' },
    { category: 'Deeply Relatable', cn: '晚上的风很大，像极了我在职场里的卑微。', en: 'The wind at night is strong, just like my humility in the workplace.' },
    { category: 'Deeply Relatable', cn: '有时候，关掉电脑才是真正的下班。', en: 'Sometimes, turning off the computer is the only true way to clock out.' },
    { category: 'Deeply Relatable', cn: '我们都在用忙碌，来掩盖灵魂的荒芜。', en: 'We all use busyness to cover the desolation of our souls.' },
    { category: 'Deeply Relatable', cn: '所谓的合群，不过是学会了在特定频率下伪装。', en: 'Fitting in is just learning how to disguise yourself at certain frequencies.' },
    { category: 'Deeply Relatable', cn: '我也想做个小孩，可世界只想要个能干活的 API。', en: 'I want to be a child, but the world just wants a working API.' },
    { category: 'Deeply Relatable', cn: '心酸的是，我不仅没赢，连输的姿势都不够好看。', en: 'The sad thing is, I didn\'t win, and even my losing posture wasn\'t pretty enough.' },
    { category: 'Deeply Relatable', cn: '那些深夜里流过的泪，都是白天没能说出口的拒绝。', en: 'Tears shed late at night are the refusals I couldn\'t voice during the day.' },
    { category: 'Deeply Relatable', cn: '我在人群里拼命点头，心里却一直在抛出 401。', en: 'I nod frantically in the crowd, while my heart keeps throwing a 401.' },
    { category: 'Deeply Relatable', cn: '最深的情绪，往往都在没有日志记录的私有作用域里。', en: 'The deepest emotions are usually in private scopes with no logging.' },
    { category: 'Deeply Relatable', cn: '生活不是电影，它没有完美的配乐和剪辑。', en: 'Life is not a movie; it lacks perfect soundtracks and editing.' },
    { category: 'Deeply Relatable', cn: '我只是累了，连更新状态码的力气都没有。', en: 'I\'m just tired, with no strength left even to update my status code.' },
    // [Sad & Hilarious - 伤感搞笑大补充]
    { category: 'Sad & Hilarious', cn: '比起单身，我更怕我的 GitHub 绿墙变白。', en: 'I fear my GitHub contribution wall turning white more than being single.' },
    { category: 'Sad & Hilarious', cn: '别问我为什么哭，问就是眼睛进了 JavaScript。', en: 'Don\'t ask why I\'m crying; ask why JavaScript got in my eyes.' },
    { category: 'Sad & Hilarious', cn: '我的存折像个递归函数，一直减到基础情况：0。', en: 'My savings account is like a recursive function, reducing to the base case: 0.' },
    { category: 'Sad & Hilarious', cn: '我以为我有对象，原来那只是个 Object。', en: 'I thought I had a partner; turns out it was just an Object.' },
    { category: 'Sad & Hilarious', cn: '我的心情像现在的汇率，跌得没完没了。', en: 'My mood is like the current exchange rate: an endless drop.' },
    { category: 'Sad & Hilarious', cn: '虽然我很惨，但我的报错日志写得很精彩。', en: 'I might be pathetic, but my error logs are fascinating.' },
    { category: 'Sad & Hilarious', cn: '我的社交能力像现在的电池，充了半天，用五分钟就没。', en: 'My social skills are like modern batteries: charging for hours, dead in five minutes.' },
    { category: 'Sad & Hilarious', cn: '如果我消失了，请帮我把我的硬盘物理销毁。', en: 'If I disappear, please physically destroy my hard drive for me.' },
    { category: 'Sad & Hilarious', cn: '我的快乐阈值已经降到了只要不蓝屏就行。', en: 'My happiness threshold has dropped to "as long as there\'s no Blue Screen."' },
    { category: 'Sad & Hilarious', cn: '我的人生没有快捷键，每一天都在 Ctrl+C 痛苦。', en: 'My life has no shortcuts; every day is Ctrl+C of pain.' },
    { category: 'Sad & Hilarious', cn: '为了梦想我卖了灵魂，结果买家嫌我灵魂版本太低。', en: 'I sold my soul for my dreams; the buyer said my soul version was too low.' },
    { category: 'Sad & Hilarious', cn: '我不是在发呆，我是在进行大脑碎片整理。', en: 'I\'m not zoning out; I\'m performing a brain defragmentation.' },
    { category: 'Sad & Hilarious', cn: '生活对我重拳出击，我只能用 try-catch 默默承受。', en: 'Life hits me with a heavy fist; I can only take it with a try-catch.' },
    { category: 'Sad & Hilarious', cn: '我这种人，在电影里通常活不过片头曲。', en: 'People like me usually don\'t survive the opening credits in a movie.' },
    { category: 'Sad & Hilarious', cn: '谢谢你出现在我生命里，让我知道了什么是死循环。', en: 'Thank you for appearing in my life; I finally know what an infinite loop is.' },
    { category: 'Sad & Hilarious', cn: '我的人生像一个 GitHub 项目，满是 issue，没人 fork。', en: 'My life is like a GitHub project: full of issues, nobody forks it.' },
    { category: 'Sad & Hilarious', cn: '别人在谈恋爱，我在和 webpack 谈崩溃。', en: 'While others fall in love, I am having a mental breakdown with webpack.' },
    { category: 'Sad & Hilarious', cn: '我问自己："今年还有希望吗？"回答是404。', en: 'I asked myself: "Is there hope this year?" The answer: 404 Not Found.' },
    { category: 'Sad & Hilarious', cn: '心碎的时候不要看手机，除非你想在 Bug 里溺水。', en: 'Do not check your phone when heartbroken, unless you want to drown in bugs.' },
    { category: 'Sad & Hilarious', cn: '失眠的你，就像一个永远没有 await 的 async 函数。', en: 'You without sleep are like an async function that never awaits its promise.' },
    { category: 'Sad & Hilarious', cn: '长大了才明白，"及时行乐"就是及时吃土。', en: 'Growing up I learned: "living for the moment" means eating dirt on time.' },
    { category: 'Sad & Hilarious', cn: '有时候我连自己都搞不定，还要去理解 TypeScript？', en: 'Sometimes I cannot figure myself out; how can I understand TypeScript?' },
    { category: 'Sad & Hilarious', cn: '她说"我们分开一段时间"，我说"这是永久分支吧"。', en: 'He said "let us take a break," I said "that is a permanent branch, right?"' },
    { category: 'Sad & Hilarious', cn: '我的快乐像 Cookie，时间到了就删除。', en: 'My happiness is like cookies: it deletes when time runs out.' },
    { category: 'Sad & Hilarious', cn: '单身就像 Debug 模式，知道问题在哪，就是改不好。', en: 'Being single is like debug mode: you know the problem, just cannot fix it.' },
    { category: 'Sad & Hilarious', cn: '工作五小时，碎片化思维八小时。', en: 'Work five hours, fragmented thinking eight hours.' },
    { category: 'Sad & Hilarious', cn: '我的梦想像 null 指针，一直找不到。', en: 'My dream is like a null pointer: never found.' },
    { category: 'Sad & Hilarious', cn: '你知道最伤心的是什么吗？是 CORS 错误。', en: 'Know what the saddest thing is? CORS errors.' },
    { category: 'Sad & Hilarious', cn: '有人说人生如戏，我的剧本是 SyntaxError。', en: 'Someone said life is like theater; my script is a SyntaxError.' },
    { category: 'Sad & Hilarious', cn: '原谅我，是因为我的每一次生气都掉了 cache。', en: 'I forgive because every time I am angry, I lose my cache.' },
    { category: 'Sad & Hilarious', cn: '感谢前任，让我懂得什么叫 undefined behavior。', en: 'Thanks to my ex, I now understand undefined behavior.' },
    { category: 'Sad & Hilarious', cn: '我和幸福之间，隔着一个栈溢出。', en: 'Between me and happiness, there is a stack overflow.' },
    { category: 'Sad & Hilarious', cn: '他们说坚持就能成功，我坚持了，然后 Timeout。', en: 'They say persistence leads to success; I persisted and got a timeout.' },
    { category: 'Sad & Hilarious', cn: '不开心的时候就想：再活几十年能怎样？反正是 deprecated。', en: 'When feeling down I think: what is the point of living decades more? I am deprecated anyway.' },
    { category: 'Sad & Hilarious', cn: '有人跑完马拉松哭了，我 while(true) 哭。', en: 'Someone cried after finishing a marathon; I am crying in a while(true) loop.' },
    { category: 'Sad & Hilarious', cn: '这个世界运行在我的眼泪上，但我没有权限 sudo。', en: 'This world runs on my tears, but I cannot sudo.' },
    { category: 'Sad & Hilarious', cn: '我的心情像 git log，全是 Revert commits。', en: 'My mood is like git log: all Revert commits.' },
    { category: 'Sad & Hilarious', cn: '有人关心我吗？有，但我设置了权限为 private。', en: 'Does anyone care about me? Yes, but I set the permission to private.' },
    { category: 'Sad & Hilarious', cn: '我用了十年升级自己，结果人设还是不兼容。', en: 'I upgraded myself for ten years; turns out I am not compatible with anyone.' },
    { category: 'Sad & Hilarious', cn: '别人的人生在 update，我的在 downgrade。', en: 'Others are upgrading their lives; mine is downgrading.' },
    { category: 'Sad & Hilarious', cn: '我配不配得到爱？我配 got 404。', en: 'Do I deserve love? I deserve 404 Not Found.' },
    { category: 'Sad & Hilarious', cn: '经历就是阅历，阅历就是伤痕，伤痕就是一个个 bug。', en: 'Experience is knowledge; knowledge is scars; scars are bugs.' },
    { category: 'Sad & Hilarious', cn: '人生最大的讽刺：越努力越失业，越专心越出 bug。', en: 'Life greatest irony: the more you work, the more unemployed you are; the more focused, the more bugs.' },
    { category: 'Sad & Hilarious', cn: '我的眼泪像内存泄漏，无限增长。', en: 'My tears are like memory leaks: infinite growth.' },
    { category: 'Sad & Hilarious', cn: '某些时刻，我是自己最大的 bug。', en: 'Sometimes, I am my own biggest bug.' },
    { category: 'Sad & Hilarious', cn: '一句"我很好"包含了多少个 WARN 日志。', en: 'How many WARN logs are hidden in one sentence: "I am fine."' },
    { category: 'Sad & Hilarious', cn: '我的生活就像没有注释的代码，连自己都看不懂。', en: 'My life is like code without comments; even I cannot understand it.' },
    { category: 'Sad & Hilarious', cn: '为什么没人喜欢我？因为我的代码质量太差。', en: 'Why does no one like me? My code quality is too poor.' },
    { category: 'Sad & Hilarious', cn: '我把眼泪存到数组里，每天 push 一个。', en: 'I store my tears in an array, pushing one every day.' },
    { category: 'Sad & Hilarious', cn: '你问我累不累？我的 console 可以告诉你。', en: 'You ask if I am tired? My console can tell you.' },
    { category: 'Sad & Hilarious', cn: '跟我相处很简单，就像跟一个死了的 API 交互。', en: 'Dating me is simple: like interacting with a dead API.' },
    { category: 'Sad & Hilarious', cn: '我身体缺氧，精神缺爱，代码缺注释。', en: 'My body lacks oxygen, my soul lacks love, my code lacks comments.' },
    { category: 'Sad & Hilarious', cn: '最后一根稻草压垮我时，我碎了，数据库也崩了。', en: 'When the last straw breaks me, I shatter and the database crashes.' },
    { category: 'Sad & Hilarious', cn: '别说我装作坚强，我只是状态码还没更新。', en: 'Do not say I am pretending to be strong; my status code just hasn\'t updated.' },
    { category: 'Sad & Hilarious', cn: '世界欠我一个拥抱和一个快速的 debug 过程。', en: 'The world owes me a hug and a quick debug session.' },
    { category: 'Sad & Hilarious', cn: '我越来越明白，有些伤是治不好的，就像无限递归。', en: 'I am learning that some wounds cannot heal, like infinite recursion.' },
]);
