/**
 * cloudModule.js
 * 体积云·大气模块定义
 * Bruneton 大气 + 体积云 raymarch + BSM 云影/丁达尔
 * 模块元数据 + 控件定义合并为一个文件
 */

import { getCloudQualityOptions, DEFAULT_CLOUD_QUALITY } from '../../modules/cloud/cloudQualityPresets';
import { translate as t } from '@common/app/useLocale';

/**
 * 创建体积云模块
 * @param {import('vue').Ref} cloudParams - 云参数 ref
 * @returns {{ id: string, title: string, description: string, status: string, statusTone: string, controls: Array }}
 */
export function createCloudModule(cloudParams) {
    const params = cloudParams.value;
    const status = params.cloudsEnabled
        ? qualityStatusLabel(params.quality)
        : t('cesium.status.disabled');
    const statusTone = params.cloudsEnabled ? 'success' : 'neutral';

    return {
        id: 'cloud',
        title: t('cesium.module.cloud.title'),
        description: t('cesium.module.cloud.description'),
        status,
        statusTone,
        controls: createCloudControls(params, !params.cloudsEnabled),
    };
}

/**
 * 构建体积云控件列表
 * @param {Record<string, any>} params - 当前云参数
 * @param {boolean} disabled - 是否禁用
 * @returns {Array<object>}
 */
function createCloudControls(params = {}, disabled) {
    const off = disabled || !params.cloudsEnabled;
    return [
        {
            id: 'cloudsEnabled',
            label: t('cesium.module.cloud.cloudsEnabled'),
            type: 'toggle',
            value: params.cloudsEnabled === true,
            tooltip: t('cesium.module.cloud.cloudsEnabledTip'),
        },
        {
            id: 'quality',
            label: t('cesium.module.cloud.quality'),
            type: 'select',
            value: params.quality ?? DEFAULT_CLOUD_QUALITY,
            options: getCloudQualityOptions().map((opt) => ({
                ...opt,
                label: t(
                    opt.value === 'balanced'
                        ? 'cesium.module.cloud.qualityBalanced'
                        : opt.value === 'ultra'
                            ? 'cesium.module.cloud.qualityUltra'
                            : 'cesium.module.cloud.qualitySmooth',
                ),
            })),
            disabled: off,
            tooltip: t('cesium.module.cloud.qualityTip'),
        },
        {
            id: 'altitudeMode',
            label: t('cesium.module.cloud.altitudeMode'),
            type: 'select',
            value: params.altitudeMode ?? 'absolute',
            options: [
                { value: 'absolute', label: t('cesium.module.cloud.altitudeModeAbsolute') },
                { value: 'terrain', label: t('cesium.module.cloud.altitudeModeTerrain') },
            ],
            disabled: off,
            tooltip: t('cesium.module.cloud.altitudeModeTip'),
        },
        {
            id: 'layer0Coverage',
            label: t('cesium.module.cloud.layer0Coverage'),
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            value: params.layer0Coverage ?? 0.3,
            displayValue: `${Math.round((params.layer0Coverage ?? 0.3) * 100)}%`,
            disabled: off,
            tooltip: t('cesium.module.cloud.layer0CoverageTip'),
        },
        {
            id: 'layer0Altitude',
            label: t('cesium.module.cloud.layer0Altitude'),
            type: 'range',
            min: 0,
            max: 8000,
            step: 50,
            value: params.layer0Altitude ?? 1800,
            displayValue: `${Math.round(params.layer0Altitude ?? 1800)} m`,
            disabled: off,
            tooltip: t('cesium.module.cloud.layer0AltitudeTip'),
        },
        {
            id: 'layer0Height',
            label: t('cesium.module.cloud.layer0Height'),
            type: 'range',
            min: 50,
            max: 5000,
            step: 50,
            value: params.layer0Height ?? 650,
            displayValue: `${Math.round(params.layer0Height ?? 650)} m`,
            disabled: off,
            tooltip: t('cesium.module.cloud.layer0HeightTip'),
        },
        {
            id: 'layer1Coverage',
            label: t('cesium.module.cloud.layer1Coverage'),
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            value: params.layer1Coverage ?? 0.3,
            displayValue: `${Math.round((params.layer1Coverage ?? 0.3) * 100)}%`,
            disabled: off,
            tooltip: t('cesium.module.cloud.layer1CoverageTip'),
        },
        {
            id: 'layer1Altitude',
            label: t('cesium.module.cloud.layer1Altitude'),
            type: 'range',
            min: 0,
            max: 12000,
            step: 50,
            value: params.layer1Altitude ?? 2400,
            displayValue: `${Math.round(params.layer1Altitude ?? 2400)} m`,
            disabled: off,
            tooltip: t('cesium.module.cloud.layer1AltitudeTip'),
        },
        {
            id: 'layer1Height',
            label: t('cesium.module.cloud.layer1Height'),
            type: 'range',
            min: 50,
            max: 6000,
            step: 50,
            value: params.layer1Height ?? 1200,
            displayValue: `${Math.round(params.layer1Height ?? 1200)} m`,
            disabled: off,
            tooltip: t('cesium.module.cloud.layer1HeightTip'),
        },
        {
            id: 'layer2Coverage',
            label: t('cesium.module.cloud.layer2Coverage'),
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            value: params.layer2Coverage ?? 0.3,
            displayValue: `${Math.round((params.layer2Coverage ?? 0.3) * 100)}%`,
            disabled: off,
            tooltip: t('cesium.module.cloud.layer2CoverageTip'),
        },
        {
            id: 'layer2Altitude',
            label: t('cesium.module.cloud.layer2Altitude'),
            type: 'range',
            min: 2000,
            max: 16000,
            step: 100,
            value: params.layer2Altitude ?? 7500,
            displayValue: `${Math.round(params.layer2Altitude ?? 7500)} m`,
            disabled: off,
            tooltip: t('cesium.module.cloud.layer2AltitudeTip'),
        },
        {
            id: 'layer2Height',
            label: t('cesium.module.cloud.layer2Height'),
            type: 'range',
            min: 50,
            max: 4000,
            step: 50,
            value: params.layer2Height ?? 500,
            displayValue: `${Math.round(params.layer2Height ?? 500)} m`,
            disabled: off,
            tooltip: t('cesium.module.cloud.layer2HeightTip'),
        },
        {
            id: 'sunIntensity',
            label: t('cesium.module.cloud.sunIntensity'),
            type: 'range',
            min: 0,
            max: 150,
            step: 1,
            value: params.sunIntensity ?? 20,
            displayValue: Number(params.sunIntensity ?? 20).toFixed(0),
            disabled: off,
            tooltip: t('cesium.module.cloud.sunIntensityTip'),
        },
        {
            id: 'cloudExposure',
            label: t('cesium.module.cloud.cloudExposure'),
            type: 'range',
            min: 0.1,
            max: 8,
            step: 0.1,
            value: params.cloudExposure ?? 3.0,
            displayValue: Number(params.cloudExposure ?? 3.0).toFixed(1),
            disabled: off,
            tooltip: t('cesium.module.cloud.cloudExposureTip'),
        },
        {
            id: 'skyToSunRatio',
            label: t('cesium.module.cloud.skyToSunRatio'),
            type: 'range',
            min: 0.05,
            max: 0.6,
            step: 0.01,
            value: params.skyToSunRatio ?? 0.28,
            displayValue: Number(params.skyToSunRatio ?? 0.28).toFixed(2),
            disabled: off,
            tooltip: t('cesium.module.cloud.skyToSunRatioTip'),
        },
        {
            id: 'aerialPerspectiveScale',
            label: t('cesium.module.cloud.aerialPerspectiveScale'),
            type: 'range',
            min: 0,
            max: 3,
            step: 0.1,
            value: params.aerialPerspectiveScale ?? 0.0,
            displayValue: Number(params.aerialPerspectiveScale ?? 0.0).toFixed(1),
            disabled: off,
            tooltip: t('cesium.module.cloud.aerialPerspectiveScaleTip'),
        },
        {
            id: 'groundAerialScale',
            label: t('cesium.module.cloud.groundAerialScale'),
            type: 'range',
            min: 0,
            max: 1,
            step: 0.05,
            value: params.groundAerialScale ?? 1.0,
            displayValue: Number(params.groundAerialScale ?? 1.0).toFixed(2),
            disabled: off || params.aerialStageEnabled === false,
            tooltip: t('cesium.module.cloud.groundAerialScaleTip'),
        },
        {
            id: 'magentaFixStrength',
            label: t('cesium.module.cloud.magentaFixStrength'),
            type: 'range',
            min: 0,
            max: 5,
            step: 0.1,
            value: params.magentaFixStrength ?? 2.0,
            displayValue: Number(params.magentaFixStrength ?? 2.0).toFixed(1),
            disabled: off,
            tooltip: t('cesium.module.cloud.magentaFixStrengthTip'),
        },
        {
            id: 'scatterG1',
            label: t('cesium.module.cloud.scatterG1'),
            type: 'range',
            min: -1,
            max: 1,
            step: 0.01,
            value: params.scatterG1 ?? 0.7,
            displayValue: Number(params.scatterG1 ?? 0.7).toFixed(2),
            disabled: off,
            tooltip: t('cesium.module.cloud.scatterG1Tip'),
        },
        {
            id: 'scatterG2',
            label: t('cesium.module.cloud.scatterG2'),
            type: 'range',
            min: -1,
            max: 1,
            step: 0.01,
            value: params.scatterG2 ?? -0.2,
            displayValue: Number(params.scatterG2 ?? -0.2).toFixed(2),
            disabled: off,
            tooltip: t('cesium.module.cloud.scatterG2Tip'),
        },
        {
            id: 'atmosphereExposureDay',
            label: t('cesium.module.cloud.atmosphereExposureDay'),
            type: 'range',
            min: 0.1,
            max: 3,
            step: 0.05,
            value: params.atmosphereExposureDay ?? 1.0,
            displayValue: Number(params.atmosphereExposureDay ?? 1.0).toFixed(2),
            disabled: off,
            tooltip: t('cesium.module.cloud.atmosphereExposureDayTip'),
        },
        {
            id: 'atmosphereExposureNight',
            label: t('cesium.module.cloud.atmosphereExposureNight'),
            type: 'range',
            min: 0.0,
            max: 1.5,
            step: 0.05,
            value: params.atmosphereExposureNight ?? 0.1,
            displayValue: Number(params.atmosphereExposureNight ?? 0.1).toFixed(2),
            disabled: off,
            tooltip: t('cesium.module.cloud.atmosphereExposureNightTip'),
        },
        {
            id: 'atmosphereExposureManual',
            label: t('cesium.module.cloud.atmosphereExposureManual'),
            type: 'range',
            min: 0.1,
            max: 5,
            step: 0.05,
            value: params.atmosphereExposureManual ?? 1.0,
            displayValue: Number(params.atmosphereExposureManual ?? 1.0).toFixed(2),
            disabled: off || params.atmosphereExposureFollowTimeline !== false,
            tooltip: t('cesium.module.cloud.atmosphereExposureManualTip'),
        },
        {
            id: 'atmosphereExposureFollowTimeline',
            label: t('cesium.module.cloud.atmosphereExposureFollowTimeline'),
            type: 'toggle',
            value: params.atmosphereExposureFollowTimeline !== false,
            disabled: off,
            tooltip: t('cesium.module.cloud.atmosphereExposureFollowTimelineTip'),
        },
        {
            id: 'atmosphereStageEnabled',
            label: t('cesium.module.cloud.atmosphereStageEnabled'),
            type: 'toggle',
            value: params.atmosphereStageEnabled !== false,
            disabled: off,
            tooltip: t('cesium.module.cloud.atmosphereStageEnabledTip'),
        },
        {
            id: 'aerialStageEnabled',
            label: t('cesium.module.cloud.aerialStageEnabled'),
            type: 'toggle',
            value: params.aerialStageEnabled !== false,
            disabled: off,
            tooltip: t('cesium.module.cloud.aerialStageEnabledTip'),
        },
        {
            id: 'windSpeed',
            label: t('cesium.module.cloud.windSpeed'),
            type: 'range',
            min: 0,
            max: 1,
            step: 0.0001,
            value: params.windSpeed ?? 0,
            displayValue: Number(params.windSpeed ?? 0).toFixed(4),
            disabled: off,
            tooltip: t('cesium.module.cloud.windSpeedTip'),
        },
        {
            id: 'evolutionSpeed',
            label: t('cesium.module.cloud.evolutionSpeed'),
            type: 'range',
            min: 0,
            max: 0.02,
            step: 0.0005,
            value: params.evolutionSpeed ?? 0.005,
            displayValue: Number(params.evolutionSpeed ?? 0.005).toFixed(4),
            disabled: off,
            tooltip: t('cesium.module.cloud.evolutionSpeedTip'),
        },
        {
            id: 'distFadeStart',
            label: t('cesium.module.cloud.distFadeStart'),
            type: 'range',
            min: 1000,
            max: 50000,
            step: 500,
            value: params.distFadeStart ?? 11000,
            displayValue: `${Math.round((params.distFadeStart ?? 11000) / 1000)} km`,
            disabled: off,
            tooltip: t('cesium.module.cloud.distFadeStartTip'),
        },
        {
            id: 'distFadeEnd',
            label: t('cesium.module.cloud.distFadeEnd'),
            type: 'range',
            min: 5000,
            max: 200000,
            step: 1000,
            value: params.distFadeEnd ?? 51000,
            displayValue: `${Math.round((params.distFadeEnd ?? 51000) / 1000)} km`,
            disabled: off,
            tooltip: t('cesium.module.cloud.distFadeEndTip'),
        },
        {
            id: 'maxRayDistance',
            label: t('cesium.module.cloud.maxRayDistance'),
            type: 'range',
            min: 10000,
            max: 300000,
            step: 5000,
            value: params.maxRayDistance ?? 200000,
            displayValue: `${Math.round((params.maxRayDistance ?? 200000) / 1000)} km`,
            disabled: off,
            tooltip: t('cesium.module.cloud.maxRayDistanceTip'),
        },
        {
            id: 'altitudeFadeRange',
            label: t('cesium.module.cloud.altitudeFadeRange'),
            type: 'range',
            min: 1000,
            max: 30000,
            step: 500,
            value: params.altitudeFadeRange ?? 8000,
            displayValue: `${Math.round((params.altitudeFadeRange ?? 8000) / 1000)} km`,
            disabled: off,
            tooltip: t('cesium.module.cloud.altitudeFadeRangeTip'),
        },
        {
            id: 'maxSteps',
            label: t('cesium.module.cloud.maxSteps'),
            type: 'range',
            min: 64,
            max: 1000,
            step: 1,
            value: params.maxSteps ?? 500,
            displayValue: String(Math.round(params.maxSteps ?? 500)),
            disabled: off,
            tooltip: t('cesium.module.cloud.maxStepsTip'),
        },
        {
            id: 'cloudResolutionScale',
            label: t('cesium.module.cloud.cloudResolutionScale'),
            type: 'range',
            min: 0.5,
            max: 1,
            step: 0.01,
            value: params.cloudResolutionScale ?? 1,
            displayValue: `${Math.round((params.cloudResolutionScale ?? 1) * 100)}%`,
            disabled: off,
            tooltip: t('cesium.module.cloud.cloudResolutionScaleTip'),
        },
        {
            id: 'minStepSize',
            label: t('cesium.module.cloud.minStepSize'),
            type: 'range',
            min: 20,
            max: 200,
            step: 1,
            value: params.minStepSize ?? 50,
            displayValue: `${Math.round(params.minStepSize ?? 50)} m`,
            disabled: off,
            tooltip: t('cesium.module.cloud.minStepSizeTip'),
        },
        {
            id: 'perspectiveStepScale',
            label: t('cesium.module.cloud.perspectiveStepScale'),
            type: 'range',
            min: 1,
            max: 1.05,
            step: 0.001,
            value: params.perspectiveStepScale ?? 1.01,
            displayValue: Number(params.perspectiveStepScale ?? 1.01).toFixed(3),
            disabled: off,
            tooltip: t('cesium.module.cloud.perspectiveStepScaleTip'),
        },
        {
            id: 'multiScatteringOctaves',
            label: t('cesium.module.cloud.multiScatteringOctaves'),
            type: 'range',
            min: 1,
            max: 12,
            step: 1,
            value: params.multiScatteringOctaves ?? 8,
            displayValue: String(Math.round(params.multiScatteringOctaves ?? 8)),
            disabled: off,
            tooltip: t('cesium.module.cloud.multiScatteringOctavesTip'),
        },
        {
            id: 'useShadowBuffer',
            label: t('cesium.module.cloud.useShadowBuffer'),
            type: 'toggle',
            value: params.useShadowBuffer !== false,
            disabled: off,
            tooltip: t('cesium.module.cloud.useShadowBufferTip'),
        },
        {
            id: 'shadowLengthEnabled',
            label: t('cesium.module.cloud.shadowLengthEnabled'),
            type: 'toggle',
            value: params.shadowLengthEnabled !== false,
            disabled: off,
            tooltip: t('cesium.module.cloud.shadowLengthEnabledTip'),
        },
        {
            id: 'bsmGroundScale',
            label: t('cesium.module.cloud.bsmGroundScale'),
            type: 'range',
            min: 0.1,
            max: 10,
            step: 0.1,
            value: params.bsmGroundScale ?? 0.1,
            displayValue: Number(params.bsmGroundScale ?? 0.1).toFixed(1),
            disabled: off || params.useShadowBuffer === false,
            tooltip: t('cesium.module.cloud.bsmGroundScaleTip'),
        },
        {
            id: 'bsmTyndallScale',
            label: t('cesium.module.cloud.bsmTyndallScale'),
            type: 'range',
            min: 0.1,
            max: 10,
            step: 0.1,
            value: params.bsmTyndallScale ?? 1.0,
            displayValue: Number(params.bsmTyndallScale ?? 1.0).toFixed(1),
            disabled: off || params.shadowLengthEnabled === false,
            tooltip: t('cesium.module.cloud.bsmTyndallScaleTip'),
        },
        {
            id: 'shadowFar',
            label: t('cesium.module.cloud.shadowFar'),
            type: 'range',
            min: 10000,
            max: 200000,
            step: 1000,
            value: params.shadowFar ?? 120000,
            displayValue: `${Math.round((params.shadowFar ?? 120000) / 1000)} km`,
            disabled: off || params.useShadowBuffer === false,
            tooltip: t('cesium.module.cloud.shadowFarTip'),
        },
        {
            id: 'shadowSplitLambda',
            label: t('cesium.module.cloud.shadowSplitLambda'),
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            value: params.shadowSplitLambda ?? 1.0,
            displayValue: Number(params.shadowSplitLambda ?? 1.0).toFixed(2),
            disabled: off || params.useShadowBuffer === false,
            tooltip: t('cesium.module.cloud.shadowSplitLambdaTip'),
        },
        {
            id: 'shadowFadeScale',
            label: t('cesium.module.cloud.shadowFadeScale'),
            type: 'range',
            min: 1,
            max: 20,
            step: 0.5,
            value: params.shadowFadeScale ?? 5.0,
            displayValue: Number(params.shadowFadeScale ?? 5.0).toFixed(1),
            disabled: off || params.useShadowBuffer === false,
            tooltip: t('cesium.module.cloud.shadowFadeScaleTip'),
        },
        {
            id: 'hazeEnabled',
            label: t('cesium.module.cloud.hazeEnabled'),
            type: 'toggle',
            value: params.hazeEnabled === true,
            disabled: off,
            tooltip: t('cesium.module.cloud.hazeEnabledTip'),
        },
        {
            id: 'temporalEnabled',
            label: t('cesium.module.cloud.temporalEnabled'),
            type: 'toggle',
            value: params.temporalEnabled === true,
            disabled: off,
            tooltip: t('cesium.module.cloud.temporalEnabledTip'),
        },
        {
            id: 'lensFlareEnabled',
            label: t('cesium.module.cloud.lensFlareEnabled'),
            type: 'toggle',
            value: params.lensFlareEnabled !== false,
            disabled: off,
            tooltip: t('cesium.module.cloud.lensFlareEnabledTip'),
        },
        {
            id: 'bloomIntensity',
            label: t('cesium.module.cloud.bloomIntensity'),
            type: 'range',
            min: 0,
            max: 3,
            step: 0.05,
            value: params.bloomIntensity ?? 0.6,
            displayValue: Number(params.bloomIntensity ?? 0.6).toFixed(2),
            disabled: off || params.lensFlareEnabled === false,
            tooltip: t('cesium.module.cloud.bloomIntensityTip'),
        },
        {
            id: 'ghostIntensity',
            label: t('cesium.module.cloud.ghostIntensity'),
            type: 'range',
            min: 0,
            max: 3,
            step: 0.05,
            value: params.ghostIntensity ?? 1.1,
            displayValue: Number(params.ghostIntensity ?? 1.1).toFixed(2),
            disabled: off || params.lensFlareEnabled === false,
            tooltip: t('cesium.module.cloud.ghostIntensityTip'),
        },
        {
            id: 'haloIntensity',
            label: t('cesium.module.cloud.haloIntensity'),
            type: 'range',
            min: 0,
            max: 2,
            step: 0.05,
            value: params.haloIntensity ?? 0.2,
            displayValue: Number(params.haloIntensity ?? 0.2).toFixed(2),
            disabled: off || params.lensFlareEnabled === false,
            tooltip: t('cesium.module.cloud.haloIntensityTip'),
        },
    ];
}

/**
 * 模块卡片状态文案：流畅 / 均衡 / 极致
 * @param {string | undefined} quality
 * @returns {string}
 */
function qualityStatusLabel(quality) {
    if (quality === 'balanced') return t('cesium.status.qualityBalanced');
    if (quality === 'ultra') return t('cesium.status.qualityUltra');
    return t('cesium.status.qualitySmooth');
}