/**
 * cloudModule.js
 * 体积云·大气模块定义
 * Bruneton 大气 + 体积云 raymarch + BSM 云影/丁达尔
 * 模块元数据 + 控件定义合并为一个文件
 */

import { getCloudQualityOptions, DEFAULT_CLOUD_QUALITY } from '../../Cloud/cloudQualityPresets';

/**
 * 创建体积云模块
 * @param {import('vue').Ref} cloudParams - 云参数 ref
 * @returns {{ id: string, title: string, description: string, status: string, statusTone: string, controls: Array }}
 */
export function createCloudModule(cloudParams) {
    const params = cloudParams.value;
    const status = params.cloudsEnabled
        ? qualityStatusLabel(params.quality)
        : '未启用';
    const statusTone = params.cloudsEnabled ? 'success' : 'neutral';

    return {
        id: 'cloud',
        title: '体积云·大气',
        description: 'Bruneton 大气 + 体积云 raymarch + BSM 云影/丁达尔（cesium-clouds-atmosphere）',
        status,
        statusTone,
        controls: createCloudControls(params, !params.cloudsEnabled),
    };
}

/**
 * 构建体积云控件列表
 * @param {Record<string, any>} params - 当前云参数
 * @param {boolean} disabled - 是否禁用
 * @returns {Array<object>}
 */
function createCloudControls(params = {}, disabled) {
    const off = disabled || !params.cloudsEnabled;
    return [
        {
            id: 'cloudsEnabled',
            label: '启用体积云·大气',
            type: 'toggle',
            value: params.cloudsEnabled === true,
            tooltip: '懒加载 Bruneton 大气 + 体积云 raymarch；默认「流畅」档，首次开启会加载约 29MB 纹理/LUT',
        },
        {
            id: 'quality',
            label: '性能预设',
            type: 'select',
            value: params.quality ?? DEFAULT_CLOUD_QUALITY,
            options: getCloudQualityOptions(),
            disabled: off,
            tooltip: '流畅=仅云；均衡=云+轻 BSM/光晕；极致=全效果高采样',
        },
        {
            id: 'layer0Coverage',
            label: '低云覆盖',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            value: params.layer0Coverage ?? 0.3,
            displayValue: `${Math.round((params.layer0Coverage ?? 0.3) * 100)}%`,
            disabled: off,
            tooltip: '低云层天气图覆盖率（0=无云 1=全覆盖）',
        },
        {
            id: 'layer0Altitude',
            label: '低云底高',
            type: 'range',
            min: 0,
            max: 8000,
            step: 50,
            value: params.layer0Altitude ?? 1800,
            displayValue: `${Math.round(params.layer0Altitude ?? 1800)} m`,
            disabled: off,
            tooltip: '低云层底部海拔高度',
        },
        {
            id: 'layer0Height',
            label: '低云厚度',
            type: 'range',
            min: 50,
            max: 5000,
            step: 50,
            value: params.layer0Height ?? 650,
            displayValue: `${Math.round(params.layer0Height ?? 650)} m`,
            disabled: off,
            tooltip: '低云层垂直厚度',
        },
        {
            id: 'layer1Coverage',
            label: '中云覆盖',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            value: params.layer1Coverage ?? 0.3,
            displayValue: `${Math.round((params.layer1Coverage ?? 0.3) * 100)}%`,
            disabled: off,
            tooltip: '中云层天气图覆盖率（0=无云 1=全覆盖）',
        },
        {
            id: 'layer1Altitude',
            label: '中云底高',
            type: 'range',
            min: 0,
            max: 12000,
            step: 50,
            value: params.layer1Altitude ?? 2400,
            displayValue: `${Math.round(params.layer1Altitude ?? 2400)} m`,
            disabled: off,
            tooltip: '中云层底部海拔高度',
        },
        {
            id: 'layer1Height',
            label: '中云厚度',
            type: 'range',
            min: 50,
            max: 6000,
            step: 50,
            value: params.layer1Height ?? 1200,
            displayValue: `${Math.round(params.layer1Height ?? 1200)} m`,
            disabled: off,
            tooltip: '中云层垂直厚度',
        },
        {
            id: 'layer2Coverage',
            label: '高云覆盖',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            value: params.layer2Coverage ?? 0.3,
            displayValue: `${Math.round((params.layer2Coverage ?? 0.3) * 100)}%`,
            disabled: off,
            tooltip: '高云层天气图覆盖率（0=无云 1=全覆盖）',
        },
        {
            id: 'layer2Altitude',
            label: '高云底高',
            type: 'range',
            min: 2000,
            max: 16000,
            step: 100,
            value: params.layer2Altitude ?? 7500,
            displayValue: `${Math.round(params.layer2Altitude ?? 7500)} m`,
            disabled: off,
            tooltip: '高云层底部海拔高度',
        },
        {
            id: 'layer2Height',
            label: '高云厚度',
            type: 'range',
            min: 50,
            max: 4000,
            step: 50,
            value: params.layer2Height ?? 500,
            displayValue: `${Math.round(params.layer2Height ?? 500)} m`,
            disabled: off,
            tooltip: '高云层垂直厚度',
        },
        {
            id: 'sunIntensity',
            label: '太阳强度',
            type: 'range',
            min: 0,
            max: 150,
            step: 1,
            value: params.sunIntensity ?? 20,
            displayValue: Number(params.sunIntensity ?? 20).toFixed(0),
            disabled: off,
            tooltip: '太阳对云的光照强度，影响云的亮度和对比度',
        },
        {
            id: 'cloudExposure',
            label: '云曝光',
            type: 'range',
            min: 0.1,
            max: 8,
            step: 0.1,
            value: params.cloudExposure ?? 3.0,
            displayValue: Number(params.cloudExposure ?? 3.0).toFixed(1),
            disabled: off,
            tooltip: '只影响云颜色，不影响底图',
        },
        {
            id: 'skyToSunRatio',
            label: '天空/太阳比',
            type: 'range',
            min: 0.05,
            max: 0.6,
            step: 0.01,
            value: params.skyToSunRatio ?? 0.28,
            displayValue: Number(params.skyToSunRatio ?? 0.28).toFixed(2),
            disabled: off,
            tooltip: '天空散射光与太阳直射光的比例，影响云的冷暖色调',
        },
        {
            id: 'aerialPerspectiveScale',
            label: '大气透视',
            type: 'range',
            min: 0,
            max: 3,
            step: 0.1,
            value: params.aerialPerspectiveScale ?? 0.0,
            displayValue: Number(params.aerialPerspectiveScale ?? 0.0).toFixed(1),
            disabled: off,
            tooltip: 'Cloud Stage 云体透视；控制远处云融入天空色的程度',
        },
        {
            id: 'groundAerialScale',
            label: '地面发白',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.05,
            value: params.groundAerialScale ?? 1.0,
            displayValue: Number(params.groundAerialScale ?? 1.0).toFixed(2),
            disabled: off || params.aerialStageEnabled === false,
            tooltip: '控制空中透视 stage 对地面的发白程度（0=原色 1=全散射），需开启「空中透视 stage」',
        },
        {
            id: 'magentaFixStrength',
            label: '去品红强度',
            type: 'range',
            min: 0,
            max: 5,
            step: 0.1,
            value: params.magentaFixStrength ?? 2.0,
            displayValue: Number(params.magentaFixStrength ?? 2.0).toFixed(1),
            disabled: off,
            tooltip: '校正体积云 raymarch 的偏品红 tint，0=不校正',
        },
        {
            id: 'scatterG1',
            label: '前向散射 G1',
            type: 'range',
            min: -1,
            max: 1,
            step: 0.01,
            value: params.scatterG1 ?? 0.7,
            displayValue: Number(params.scatterG1 ?? 0.7).toFixed(2),
            disabled: off,
            tooltip: 'Henyey-Greenstein 前向散射权重（正=前向亮）',
        },
        {
            id: 'scatterG2',
            label: '后向散射 G2',
            type: 'range',
            min: -1,
            max: 1,
            step: 0.01,
            value: params.scatterG2 ?? -0.2,
            displayValue: Number(params.scatterG2 ?? -0.2).toFixed(2),
            disabled: off,
            tooltip: 'Henyey-Greenstein 后向散射权重（负=逆光暗）',
        },
        {
            id: 'atmosphereExposureDay',
            label: '大气曝光(白天)',
            type: 'range',
            min: 0.1,
            max: 3,
            step: 0.05,
            value: params.atmosphereExposureDay ?? 1.0,
            displayValue: Number(params.atmosphereExposureDay ?? 1.0).toFixed(2),
            disabled: off,
            tooltip: '乘到所有像素（含底图）；>1 会让底图偏白',
        },
        {
            id: 'atmosphereExposureNight',
            label: '大气曝光(夜晚)',
            type: 'range',
            min: 0.0,
            max: 1.5,
            step: 0.05,
            value: params.atmosphereExposureNight ?? 0.1,
            displayValue: Number(params.atmosphereExposureNight ?? 0.1).toFixed(2),
            disabled: off,
            tooltip: '夜间大气曝光倍率，控制夜景亮度',
        },
        {
            id: 'atmosphereExposureManual',
            label: '大气曝光(手动)',
            type: 'range',
            min: 0.1,
            max: 5,
            step: 0.05,
            value: params.atmosphereExposureManual ?? 1.0,
            displayValue: Number(params.atmosphereExposureManual ?? 1.0).toFixed(2),
            disabled: off || params.atmosphereExposureFollowTimeline !== false,
            tooltip: '关闭「曝光随时间轴」后生效',
        },
        {
            id: 'atmosphereExposureFollowTimeline',
            label: '曝光随时间轴',
            type: 'toggle',
            value: params.atmosphereExposureFollowTimeline !== false,
            disabled: off,
            tooltip: '曝光随 Cesium 时间轴自动切换日夜（关闭后用手动值）',
        },
        {
            id: 'atmosphereStageEnabled',
            label: 'Bruneton 天空',
            type: 'toggle',
            value: params.atmosphereStageEnabled !== false,
            disabled: off,
            tooltip: '关闭后只保留体积云 stage，天空回退为透传场景色',
        },
        {
            id: 'aerialStageEnabled',
            label: '空中透视 stage',
            type: 'toggle',
            value: params.aerialStageEnabled !== false,
            disabled: off,
            tooltip: '链末端 ACES/几何透视；流畅档默认关闭以省 GPU',
        },
        {
            id: 'windSpeed',
            label: '风速',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.0001,
            value: params.windSpeed ?? 0,
            displayValue: Number(params.windSpeed ?? 0).toFixed(4),
            disabled: off,
            tooltip: '云水平漂移速度（纹理坐标偏移），0=静止',
        },
        {
            id: 'evolutionSpeed',
            label: '云演化速度',
            type: 'range',
            min: 0,
            max: 0.02,
            step: 0.0005,
            value: params.evolutionSpeed ?? 0.005,
            displayValue: Number(params.evolutionSpeed ?? 0.005).toFixed(4),
            disabled: off,
            tooltip: '云形态演化速度（噪声时间轴推进），0=冻结',
        },
        {
            id: 'distFadeStart',
            label: '距离衰减起始',
            type: 'range',
            min: 1000,
            max: 50000,
            step: 500,
            value: params.distFadeStart ?? 11000,
            displayValue: `${Math.round((params.distFadeStart ?? 11000) / 1000)} km`,
            disabled: off,
            tooltip: '云入口距离超过此值开始线性衰减 alpha（流畅 10km / 均衡 10km / 极致 11km）',
        },
        {
            id: 'distFadeEnd',
            label: '距离衰减结束',
            type: 'range',
            min: 5000,
            max: 200000,
            step: 1000,
            value: params.distFadeEnd ?? 51000,
            displayValue: `${Math.round((params.distFadeEnd ?? 51000) / 1000)} km`,
            disabled: off,
            tooltip: '云入口距离达到此值 alpha 完全归零',
        },
        {
            id: 'maxRayDistance',
            label: '最大采样距离',
            type: 'range',
            min: 10000,
            max: 300000,
            step: 5000,
            value: params.maxRayDistance ?? 200000,
            displayValue: `${Math.round((params.maxRayDistance ?? 200000) / 1000)} km`,
            disabled: off,
            tooltip: 'raymarch 最大射线距离；应 > distFadeEnd（流畅 50km / 均衡/极致 200km）',
        },
        {
            id: 'altitudeFadeRange',
            label: '高度淡出范围',
            type: 'range',
            min: 1000,
            max: 30000,
            step: 500,
            value: params.altitudeFadeRange ?? 8000,
            displayValue: `${Math.round((params.altitudeFadeRange ?? 8000) / 1000)} km`,
            disabled: off,
            tooltip: '相机升过云顶后在此范围内线性淡出（防止突然消失）；0=不平滑',
        },
        {
            id: 'maxSteps',
            label: '主采样步数',
            type: 'range',
            min: 64,
            max: 1000,
            step: 1,
            value: params.maxSteps ?? 500,
            displayValue: String(Math.round(params.maxSteps ?? 500)),
            disabled: off,
            tooltip: '越大越清晰但越耗 GPU（流畅约 220 / 均衡约 280 / 极致 500）',
        },
        {
            id: 'multiScatteringOctaves',
            label: '多散射阶数',
            type: 'range',
            min: 1,
            max: 12,
            step: 1,
            value: params.multiScatteringOctaves ?? 8,
            displayValue: String(Math.round(params.multiScatteringOctaves ?? 8)),
            disabled: off,
            tooltip: '多次散射迭代次数，越多云越通透但越耗 GPU',
        },
        {
            id: 'useShadowBuffer',
            label: 'BSM 云阴影',
            type: 'toggle',
            value: params.useShadowBuffer !== false,
            disabled: off,
            tooltip: 'Beer Shadow Map：云对地面投影（流畅档关闭）',
        },
        {
            id: 'shadowLengthEnabled',
            label: '丁达尔光柱',
            type: 'toggle',
            value: params.shadowLengthEnabled !== false,
            disabled: off,
            tooltip: '阴影长度采样（流畅档关闭）',
        },
        {
            id: 'bsmGroundScale',
            label: '地面阴影强度',
            type: 'range',
            min: 0.1,
            max: 10,
            step: 0.1,
            value: params.bsmGroundScale ?? 0.1,
            displayValue: Number(params.bsmGroundScale ?? 0.1).toFixed(1),
            disabled: off || params.useShadowBuffer === false,
            tooltip: 'BSM 云影在地面的光学深度缩放，值越大阴影越深',
        },
        {
            id: 'bsmTyndallScale',
            label: '光柱强度',
            type: 'range',
            min: 0.1,
            max: 10,
            step: 0.1,
            value: params.bsmTyndallScale ?? 1.0,
            displayValue: Number(params.bsmTyndallScale ?? 1.0).toFixed(1),
            disabled: off || params.shadowLengthEnabled === false,
            tooltip: '丁达尔光柱的光学深度缩放，值越大光柱越明显',
        },
        {
            id: 'shadowFar',
            label: '阴影覆盖距离',
            type: 'range',
            min: 10000,
            max: 200000,
            step: 1000,
            value: params.shadowFar ?? 120000,
            displayValue: `${Math.round((params.shadowFar ?? 120000) / 1000)} km`,
            disabled: off || params.useShadowBuffer === false,
            tooltip: 'BSM 级联阴影覆盖的最远距离，应 ≤ maxRayDistance；过大影响帧率',
        },
        {
            id: 'shadowSplitLambda',
            label: '阴影级联分配',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            value: params.shadowSplitLambda ?? 1.0,
            displayValue: Number(params.shadowSplitLambda ?? 1.0).toFixed(2),
            disabled: off || params.useShadowBuffer === false,
            tooltip: 'BSM cascade 近处分配权重（0=均匀 1=偏近处）',
        },
        {
            id: 'shadowFadeScale',
            label: '阴影衰减范围',
            type: 'range',
            min: 1,
            max: 20,
            step: 0.5,
            value: params.shadowFadeScale ?? 5.0,
            displayValue: Number(params.shadowFadeScale ?? 5.0).toFixed(1),
            disabled: off || params.useShadowBuffer === false,
            tooltip: '扩大 BSM ortho 覆盖半径，防止级联矩形外硬切',
        },
        {
            id: 'hazeEnabled',
            label: '雾霾',
            type: 'toggle',
            value: params.hazeEnabled === true,
            disabled: off,
            tooltip: '启用大气雾霾层（低空薄雾效果）',
        },
        {
            id: 'temporalEnabled',
            label: 'TAA 时序滤波',
            type: 'toggle',
            value: params.temporalEnabled === true,
            disabled: off,
            tooltip: '原生 WebGL PBO 时序抗锯齿，可能与部分 GPU 驱动不兼容',
        },
        {
            id: 'lensFlareEnabled',
            label: '镜头光晕',
            type: 'toggle',
            value: params.lensFlareEnabled !== false,
            disabled: off,
            tooltip: '流畅档默认关闭',
        },
        {
            id: 'bloomIntensity',
            label: '光晕 Bloom',
            type: 'range',
            min: 0,
            max: 3,
            step: 0.05,
            value: params.bloomIntensity ?? 0.6,
            displayValue: Number(params.bloomIntensity ?? 0.6).toFixed(2),
            disabled: off || params.lensFlareEnabled === false,
            tooltip: '镜头光晕 Bloom 扩散强度',
        },
        {
            id: 'ghostIntensity',
            label: '鬼影强度',
            type: 'range',
            min: 0,
            max: 3,
            step: 0.05,
            value: params.ghostIntensity ?? 1.1,
            displayValue: Number(params.ghostIntensity ?? 1.1).toFixed(2),
            disabled: off || params.lensFlareEnabled === false,
            tooltip: '镜头光晕鬼影（多个光圈）强度',
        },
        {
            id: 'haloIntensity',
            label: 'Halo 强度',
            type: 'range',
            min: 0,
            max: 2,
            step: 0.05,
            value: params.haloIntensity ?? 0.2,
            displayValue: Number(params.haloIntensity ?? 0.2).toFixed(2),
            disabled: off || params.lensFlareEnabled === false,
            tooltip: '镜头光晕 Halo 光环强度',
        },
    ];
}

/**
 * 模块卡片状态文案：流畅 / 均衡 / 极致
 * @param {string | undefined} quality
 * @returns {string}
 */
function qualityStatusLabel(quality) {
    if (quality === 'balanced') return '均衡';
    if (quality === 'ultra') return '极致';
    return '流畅';
}